-- ── Trunk Comms phase 9: seed master checklist items ─────────
-- Two starter items per spec section 6a. The third spec'd
-- item ("Send Confirmation Letter") is auto-generated by phase
-- 4's schedule trigger when the Confirmation Letter template +
-- 60-day schedule are seeded (phase 13), so we don't manually
-- seed it here.
--
-- Idempotent — uses NOT EXISTS guards on title.
-- ============================================================

INSERT INTO public.trunk_show_checklist_master
  (title, description, days_before_event_start, assigned_to_role, linked_action_type, display_order, is_active)
SELECT 'Confirm postcard order',
       'Order postcards via the marketing portal at least 60 days before the event so they arrive in time.',
       60, 'rep', 'marketing_postcard', 1, true
WHERE NOT EXISTS (
  SELECT 1 FROM public.trunk_show_checklist_master WHERE title = 'Confirm postcard order'
);

INSERT INTO public.trunk_show_checklist_master
  (title, description, days_before_event_start, assigned_to_role, linked_action_type, display_order, is_active)
SELECT 'Confirm counter cards',
       'Verify counter card design + quantity with the store, and place the order.',
       30, 'rep', 'none', 2, true
WHERE NOT EXISTS (
  SELECT 1 FROM public.trunk_show_checklist_master WHERE title = 'Confirm counter cards'
);

DO $$ BEGIN
  RAISE NOTICE 'Master checklist seeded with 2 starter items.';
END $$;
