-- ============================================================
-- One-shot loose-match tagger: link every trunk_show_stores row
-- to the RJO trade organization if its name fuzzy-matches one of
-- the 1136 RJO member names.
--
-- Strategy:
--   1. Normalize both sides — lowercase, strip apostrophes/commas/
--      periods, drop trailing " - <suffix>" (location codes like
--      "- AZ", "- Selma") and drop trailing legal suffixes
--      ("Inc", "LLC", "Ltd", "Co", "Company").
--   2. Use pg_trgm similarity() on the normalized names. Threshold
--      0.30 (loose) — catches name variants AND minor differences
--      like punctuation, suffixes, location qualifiers.
--   3. For each trunk_show_stores row, take its single best match
--      (highest similarity above threshold) and insert the tag.
--
-- Re-runnable: store_trade_organization_members has a composite
-- primary key so previously-tagged stores stay tagged.
--
-- After running, the SELECT at the bottom shows EVERY
-- trunk_show_stores row with its match status + best-similarity
-- score so you can audit / hand-tag / hand-untag from there.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

WITH
-- Inline RJO list.
rjo_raw(name) AS (
  VALUES
  ('5th Avenue Jewelers'),
  ('A & J Jewelers'),
  ('A. L. Terry Jewelers'),
  ('ART Jewelers'),
  ('AZ Fine Jewelry and Repair'),
  ('Abby''s Gold and Gems'),
  ('Abernathy Fine Jewelers'),
  ('Ace of Diamonds'),
  ('Adams Jewelers VA NC'),
  ('Adler''s Diamonds'),
  ('Alan Sutton Jewelry'),
  ('Albert''s Diamond Jewelers - IN'),
  ('Albert''s Jewelers, Inc.- GA'),
  ('Albert''s Jewelry & Awards - ME'),
  ('Alexander Fine Jewelers - MI'),
  ('Alexander''s Jewelry - PA'),
  ('Alicia Fine Jewelers'),
  ('Allain''s Jewelry & Trophy Shop Inc.'),
  ('Allan Jewelers - Shenango Rd.'),
  ('Allan Jewelers -3rd St.'),
  ('Allen''s Fine Jewelry - Winona'),
  ('Allen''s Fine Jewelry- Grenada'),
  ('Allen''s Jewelers- Jacksonville'),
  ('Allison''s Fine Jewelry'),
  ('Alpine Jewelers'),
  ('Altemueller Jewelry'),
  ('Ambassador Diamond Jewelers'),
  ('Amber''s Designs'),
  ('Amor Fine Jewelry - NY'),
  ('Amore'' Jewelers - FL'),
  ('Amos Jewelry'),
  ('Amy & Co. Fine Jewelry'),
  ('Anderson Jewelry- Minden'),
  ('Anderson''s Jewelry - Effingham'),
  ('Anderson''s Jewelry - Yazoo City'),
  ('Andersons Diamond Jewelers - SC'),
  ('Andrew Z Diamonds -  Anthem'),
  ('Andrew Z Diamonds - Carefree'),
  ('Andrew Z Diamonds - Scottsdale'),
  ('Andy''s Jewelry  - Lafayette'),
  ('Anfesa''s Jewelers, Inc'),
  ('Ann Booth Jewelers'),
  ('Annapolis Jewelers'),
  ('Anne-Marie''s Fine Jewelry'),
  ('Anthony Jewelers'),
  ('Apland Jewelers'),
  ('Armbruster Jewelers'),
  ('Arnett''s Fine Jewelry'),
  ('Arney Guess Goldsmith'),
  ('Arthur''s Jewelry'),
  ('Ashland City Jewelers & Pawn'),
  ('Asmar Jewelz'),
  ('Aspen Jewelry Designs, Inc'),
  ('Atchison''s Jewelry'),
  ('Aurora Jewelers'),
  ('Avitabile Fine Jewelers'),
  ('Avonlea Jewelers LLC'),
  ('Ayers Jewelers Co. (Lee) - WI'),
  ('B & L Jewelers'),
  ('B&E Jewelers & Gemologists'),
  ('Bachman Jewelers, Inc'),
  ('Bacon Jewelers'),
  ('Bailey''s Jewelers'),
  ('Baker & Baker - OH'),
  ('Baker''s Jewelry - IL'),
  ('Baker''s Jewelry, Inc. - MT'),
  ('Balefire Goods'),
  ('Ballard & Ballard Jewelers'),
  ('Banks Jewelers - NC'),
  ('Barnes Diamonds & Designs - WI'),
  ('Barnes Fine Jewelers, Inc. - AZ'),
  ('Barnett Jewelers'),
  ('Barnhardt Jewelers, Inc'),
  ('Barry Coats Jewelers - Livingston'),
  ('Bartelsmeyer Jewelry'),
  ('Basch Jewelers, Inc. (Don)-Mac'),
  ('Basch''s Moment in Time-N Olmst'),
  ('Bauble Patch Jewelers'),
  ('Bauer Jewelers & Gemologists, Inc.-IN'),
  ('Bauer''s Jewelry Inc. - MICHIGAN'),
  ('Bay Area Diamond Co., LLC'),
  ('Bay Street Jewelers, Inc. - SC'),
  ('Bayside Coin & Jewelry - WA'),
  ('Bea''s Jewelers'),
  ('Becker Jewelers - IL'),
  ('Becker''s Jewelers, Inc. - IA'),
  ('Beeghly & Co. Jewelers & Gemologists-G'),
  ('Beeghly & Keim Jewelers & Gemologists-S'),
  ('Bell Jewelers - TN'),
  ('Bella Cosa Jewelers-IL'),
  ('Bella Design Jewelers - Chagrin Falls'),
  ('Bella Jule Fine Jewelry'),
  ('Bellman Jewelers'),
  ('Ben David Jewelers'),
  ('Bennion Jewelers'),
  ('Benqueil''s Jewelry, Inc.'),
  ('Berg Jewelry'),
  ('Bergey Jewelry - MH'),
  ('Bergey Jewelry- Oregon'),
  ('Berilian Jewelers'),
  ('Bethany''s Jewelry and Design'),
  ('Better Bling Studio'),
  ('Bichsel Jewelry'),
  ('Big Ben Jewelers'),
  ('Bill French Jewelers, LLC'),
  ('Bits of Gold Jewelry & Gifts'),
  ('Blackmon''s Jewelry Repair & Mfg.'),
  ('Blanchard Jewelers, Gary'),
  ('Bland''s Jewelry LLC'),
  ('Blanquart Jewelers - B'),
  ('Blase DeNatale Jewelers'),
  ('Bling Jewelers'),
  ('Blocher Jewelers'),
  ('Blue Diamond (The)'),
  ('Blue Water Jewelers'),
  ('Bluestone Jewelry, Inc.'),
  ('Bohland Jewelers'),
  ('Boucher Jewelers'),
  ('Bowers Jewelers - H'),
  ('Bowers Jewelry - W'),
  ('Boyer''s Diamonds'),
  ('Boyle Jewelers, Inc.'),
  ('Bradley''s Jewelers Inc'),
  ('Bradow Jewelers - WI'),
  ('Bradshaw''s Jewelers'),
  ('Branham''s Jewelry'),
  ('Brax Jewelers'),
  ('Bremer Jewelry'),
  ('Bridgewater Jewelers'),
  ('Britt Jewelry - MS'),
  ('Brittany''s Fine Jewelry, Inc.'),
  ('Britton Jewelers, LTD'),
  ('Brockhaus Jewelry'),
  ('Brown Goldsmiths'),
  ('Brown Jewelry - MT'),
  ('Bryan Jewelry - Alabama'),
  ('Bryan and Son Fine Jewelers'),
  ('Buchkosky Jewelers'),
  ('Buck''s Jewelry'),
  ('Bullock''s Jewelry'),
  ('Bulow Jewelers'),
  ('Burke''s Inc'),
  ('Burnell''s Fine Jewelry and Design'),
  ('Butler & Company, K E - GA'),
  ('Butler Diamonds and Fine Jewelry - Selma'),
  ('CBC Fine Jewelers - El Paso'),
  ('CC Jewelers - Traverse City'),
  ('CDI Diamonds & Jewelry'),
  ('CMK Jewelers and Repair LLC'),
  ('CMS Fine Jewelers'),
  ('CR Diamonds & Gems'),
  ('Caesar''s Jewelers'),
  ('Cahill-Pribyl Jewelry & Gifts'),
  ('Calhoun''s Jewelers'),
  ('Cameo Jewelers'),
  ('Capper Jewelry LLC'),
  ('Caratti Jewelers, Inc.'),
  ('Carlson Brothers Jewelry -WA'),
  ('Carlson''s Jewelers - MD'),
  ('Carroll - Ochs Jewelers'),
  ('Carroll''s Jewelers'),
  ('Cartersville Jewelry Exchange'),
  ('Castle Rocks and Jewelry'),
  ('Catawba Island Jewelers'),
  ('Caves Jewelry'),
  ('Central Jewelry Company'),
  ('Champaign Jewelers'),
  ('Chapman Jewelry & Repairs, Inc.'),
  ('Chappuis'),
  ('Charland Jewelers'),
  ('Charles Lynn Jewelers'),
  ('Cheryl Burchell Goldsmiths'),
  ('Chilson Jewelers - C'),
  ('Chipper''s Jewelry'),
  ('Chrey''s Jewelry'),
  ('Christensen Jewelers LLC - Marshfield'),
  ('Christensen Jewelry - Hampton'),
  ('Christopher''s Fine Jewelry'),
  ('Cindi''s Diamond and Jewelry Gallery'),
  ('Clark Jewelers - KY'),
  ('Clark''s Diamond Jewelers - ID'),
  ('Clark''s Jewelry Store - OH'),
  ('Clarkes Jewelers - LA'),
  ('Clarkson Jewelers - MO'),
  ('Clarksville Jewelers - TN'),
  ('Classic Designs Jewelry, Inc -CA'),
  ('Classique Jewelers, Inc.-TX'),
  ('Clater Jewelers'),
  ('Cleveland Jewelers Inc./ Coats'),
  ('Cline Jewelers'),
  ('Clinton Jewelers'),
  ('Clodius & Co. Jewelers'),
  ('Clonts Jewelry'),
  ('Coastal Jewelers'),
  ('Coffin & Trout Jewelers'),
  ('Collard Jewelers'),
  ('Colonial Jewelers'),
  ('Comfort and Son Jewelers'),
  ('Cone Jewelers - NM'),
  ('Cook Jeweler, Inc(Tom) - Daytona Beach'),
  ('Cook''s Jewelry LLC - Carrollton'),
  ('Cooper & Binkley Jewelers'),
  ('Cooper''s Fine Jewelry - FL'),
  ('Corinth Jewelers - MS'),
  ('Cornerstone Jewelers -KY'),
  ('Cornerstone Jewelry and Repair - MO'),
  ('Corwin''s  Main Street Jewelers'),
  ('Cottage Hill Diamonds'),
  ('Couch''s Jewelers'),
  ('Courtyard Mfg. Jewelers, LLC'),
  ('Cowardin''s Jewelers'),
  ('Cozzi Jewelers'),
  ('Craig Husar Fine Diamonds'),
  ('Cravens & Lewis Jewelers'),
  ('Crawford''s Jewelers Inc'),
  ('Creative Jewelers - AL'),
  ('Creative Jewelers - NC'),
  ('Cresalia Jewelers'),
  ('Crescent Jewelry'),
  ('Crews Jewelry'),
  ('Crider Quality Jewelers'),
  ('Croft & Stern Jewelry Designs'),
  ('Crown Jewelers- Virginia'),
  ('Crown Jewelry, Inc. - OK'),
  ('Cryan Jewelers, John S.'),
  ('Culy''s Jewelry, LLC'),
  ('Cunningham Jewelers'),
  ('Custom Jewelry, Inc'),
  ('Cyrus Jewelers'),
  ('D&D Jewelers - IL'),
  ('D-Lux Jewelers Inc'),
  ('DJ''s Jewelry & Gift'),
  ('DK Jewelers Inc.'),
  ('Dahlkemper''s Jewelry Connection'),
  ('Dan Gould Jewelers - A'),
  ('Dan Martin Jewelers LLC'),
  ('Dannels Jewelry'),
  ('Danwerke International'),
  ('Danz Jewelers- L'),
  ('Dave Askew Jewelers, LLC'),
  ('Dave''s Jewelry'),
  ('David Charles Ltd'),
  ('David Douglas Diamonds & Jewelry'),
  ('David''s Fine Jewelry - Breux Bridge'),
  ('Davis Jeweler, Thomas A. -MI'),
  ('Davis Jewelers - GA'),
  ('DeAngelis Jewelers'),
  ('DeVries Jewelry Store'),
  ('Dean''s Jewelry'),
  ('Deep South Gold'),
  ('Del Haven Jewelers'),
  ('Dempsey''s Jewelers'),
  ('Designer''s Circle'),
  ('Designs by Aaron'),
  ('Diamond & Designs - MN'),
  ('Diamond Classics'),
  ('Diamond Design by Bodis - WI'),
  ('Diamond Designs - IL'),
  ('Diamond Direct - Brea CA'),
  ('Diamond Durrell''s'),
  ('Diamond Jewelers - AL'),
  ('Diamond Jim''s - Phoenix'),
  ('Diamond Rush - NC'),
  ('Diamond Shop, The - IDAHO'),
  ('Diamond Showcase'),
  ('Diamond Store, The -Mitchell'),
  ('Diamonds By Dawn'),
  ('Diamonds Direct Inc. - FLORIDA'),
  ('Diamonds Evermore'),
  ('Diamonds On Wabash'),
  ('Diamonds and Dogs'),
  ('Diamonds and Gold International, Inc.-MN'),
  ('Diamonds and More Inc'),
  ('Diedrich Jewelers'),
  ('Disinger Jewelers of Jasper'),
  ('Dolabany Jewelers, Inc'),
  ('Doland Jewelers'),
  ('Don Victor Jewelers'),
  ('Don''s Jewelry & Design-Washington'),
  ('Don''s Jewelry, Inc. - Clinton'),
  ('Douglas Jeweler Inc.'),
  ('Drake''s Jewelry'),
  ('Dream Jewelers'),
  ('Drenon Jewelry, Inc.'),
  ('Droste''s Jewelry Shoppes'),
  ('Dunbar Jewelers'),
  ('Duncan Jewelry - Osage Beach'),
  ('Dunkin''s Diamonds - Naples'),
  ('Duquet Fine Jewelry Design, Christopher'),
  ('Duvarney Jewelers-C'),
  ('Duvarney Jewelers-F'),
  ('E. Ryan Jewelers'),
  ('EKA Jewelers'),
  ('East Tennessee Diamond Co, Inc.'),
  ('Eaton Turner Jewelry - Helena'),
  ('Eaton''s Fine Jewelry - St Albans'),
  ('Eckerman''s, Inc.-IA'),
  ('Ed & Ethel''s Fine Jewelry'),
  ('Eden Jewelry & Repair - Eden'),
  ('Eden Jewelry (Danville)'),
  ('Eden Jewelry Stores - South Boston'),
  ('Eden Jewelry and Repair of Martinsville, VA'),
  ('Ediger''s Diamonds'),
  ('Edmund''s Jewelers'),
  ('Edward Jewelers, M.- MA'),
  ('Elebash Jewelry Company'),
  ('Elegance Jewelers'),
  ('Elias Diamonds & Repair-T'),
  ('Ell''s Jewelry - Shawnee'),
  ('Elliott Jewelers, Inc.-IA'),
  ('Elliott''s Jewelers - Huntsville'),
  ('Ellis Jewelers - Frankfort'),
  ('Ellis Jewelers - Lexington'),
  ('Ellis Jewelers Inc. - Concord'),
  ('Ellis Jewelers, Inc - Seymour'),
  ('Ellsworth Jewelers'),
  ('Elmquist, Inc.'),
  ('Emigh Jewelry Company (EJC)'),
  ('Engelbert''s Jewelers, Inc.'),
  ('Enhancery Jewelers - CA'),
  ('Eric''s Diamonds - WI'),
  ('Erica DelGardo Jewelry Designs'),
  ('Erica''s Jewelry - IL'),
  ('Erickson Jewelers'),
  ('Erwin''s Jewelers Co'),
  ('FORGE Jewelry Works'),
  ('Faini'),
  ('Falkenberg''s Inc.'),
  ('Falmouth Jewelry Shop'),
  ('Family & Co Jewelers'),
  ('Family JewelBox LLC'),
  ('Farmer''s Jewelry, Inc., W. L.'),
  ('Farr''s Jewelry - UT'),
  ('Farrar Jewelers - NC'),
  ('Federal Way Jewelers'),
  ('Feldstein Jewelers'),
  ('Fernbaugh''s Diamonds and Fine Jewelry'),
  ('Fiebig Jewelers Inc'),
  ('Fielding Jewelry, Inc'),
  ('Finch Jewelers'),
  ('Fire and Ice Jewelry'),
  ('First People''s Jewelers'),
  ('Fliegauf Jewelers Inc.'),
  ('Floyd & Green Fine Jewelers'),
  ('Forbes Jewelers'),
  ('Forever Young Fine Jewelers'),
  ('Fountain City Jewelers'),
  ('Fox Fine Jewelry'),
  ('Frank Jewelers of Freeport'),
  ('Frantz Diamonds & Jewelry'),
  ('Franzetti Jewelers'),
  ('Furnari Jewelers'),
  ('Futer Bros, Inc'),
  ('G&H Jewelers'),
  ('G.A. Pope Fine Jewelry'),
  ('Gaines Jewelry'),
  ('Gala Jewelers, Inc.'),
  ('Galicia Fine Jewelers'),
  ('Galleria Fine Jewelry'),
  ('Garrick Jewelers, Inc.'),
  ('Gayle''s Jewelers, Inc.'),
  ('Gem Den LLC'),
  ('Gem Gallery - Bozeman'),
  ('Gem Jewelers of Ada, Inc.'),
  ('Gem Smith Inc. (The)-UT'),
  ('Gemma Gallery - Pinehurst'),
  ('Gemstone Creations, LLC'),
  ('Gendron''s Jewelers'),
  ('Genesis Jewelers of Yorktown'),
  ('Geneva Jewelry'),
  ('Genna Jewelers'),
  ('Georgetown Jewelers'),
  ('Gerald''s Jewelry - WA'),
  ('Germani''s Jewelry Inc.'),
  ('Gerster Jewelry'),
  ('Gervais Diamond Center - MON'),
  ('Gervais Jewelry & Gifts - MOR'),
  ('Gholson Originals Fine Jewelry'),
  ('Gilbert Jewelers'),
  ('Glasscock Jewelry Corner, Inc.'),
  ('Glennpeter Jewelers'),
  ('Godwin Jewelers Inc.'),
  ('Gold & Gems Fine Jewelry - OR'),
  ('Gold Corner (The) - KS'),
  ('Gold Designs Inc - Bradenton'),
  ('Gold In Art Jewelers - Mount Dora'),
  ('Gold Mine Fine Jewelry - North Carolina'),
  ('Gold Mine Jewelers- California'),
  ('Gold Rush Jewelers- Prudenville'),
  ('Gold Thumb Jewelry Creations Inc'),
  ('Gold and More Jewelers - Liberty'),
  ('Golden Dreams Jewelry- MS'),
  ('Golden Gifts Jewelry - PA'),
  ('Goldmine Jewelry- Saint Ignace'),
  ('Goldsmith Co.Jewelers - UT'),
  ('Goldsmith Gallery - AK'),
  ('Goldsmith Gallery Jewelers - MT'),
  ('Goldsmith Gallery LTD- IA'),
  ('Goldsmith, (The)-WI'),
  ('Goldstein - Pitard - AL'),
  ('Goldworks - Half Moon Bay'),
  ('Goodman & Sons Jewelers - VA'),
  ('Goodman Jewelers of Abingdon'),
  ('Goodman Jewelers of Chilhowie'),
  ('Grace Jewelers - Black Mountain'),
  ('Grace Jewelry - Columbus'),
  ('Grace Marie'),
  ('Grader Jewelers, Inc.'),
  ('Graeber Jewelers'),
  ('Graham Jewelers - Wayzata'),
  ('Graham Jewelers - White Bear Lake'),
  ('Graham Jewelry - Comanche OK'),
  ('Grant Laughter Jewelry, Inc'),
  ('Gray Jewelers, E.B.- Tennessee'),
  ('Gray''s Jewelry & Gifts-B'),
  ('Green Brothers Jewelers - TEXAS'),
  ('Green''s Jewelers Inc  Roxboro'),
  ('Greg Beckman Jewelers, Inc.'),
  ('Greg Lynn Jewelers Inc.'),
  ('Gregory Jewelers - Morganton'),
  ('Gregory''s Jewelers Inc - Lillington'),
  ('Griffith Jewelers'),
  ('Griner Jewelry'),
  ('Gross, Paul Jewelers'),
  ('Gwen''s Fine Jewelers'),
  ('Hager Jewelry Inc.'),
  ('Hall of Greetings, Inc./Greetings Jewelers'),
  ('Hamilton Jewelers'),
  ('Hancock Jewelers'),
  ('Hannon Jeweler, (Warren)'),
  ('Hanson''s Fine Jewelry-A'),
  ('Harkleroad Diamonds and Fine Jewelry'),
  ('Harold''s Jewelry Store-MO'),
  ('Harper Jewelry Co., Inc'),
  ('Harris Jeweler   - OH'),
  ('Harris Jewelers - Rio Rancho'),
  ('Harrison''s Jewelry Company- WA'),
  ('Hart''s Jewelry - NY'),
  ('Hart''s Jewelry-MI'),
  ('Hartman Jewelers'),
  ('Harvey Oaks Jeweler'),
  ('Hawthorne Jewelry'),
  ('Hayden Jewelers'),
  ('Hayman, David Jewellers'),
  ('Haywood''s Inc. - Rocky Mount'),
  ('Heiser''s Jewelry'),
  ('Heisey''s Jewelry Company'),
  ('Helker Jewelry - Platteville'),
  ('Hellberg''s Jewelers'),
  ('Heller Jewelers - San Ramon'),
  ('Henderson & Co Jewelers, Inc'),
  ('Henley Jewelers, Inc.'),
  ('Henry''s Fine Jewelry - Basking Ridge'),
  ('Henry''s Fine Jewelry - Summit'),
  ('Herberts Ltd.'),
  ('Heritage Jewelers'),
  ('Herteen & Stocker, Inc.'),
  ('Herzog Jewelers'),
  ('Hi Ho Silver, Inc'),
  ('Hill''s In-House Jewelers LLC'),
  ('Hillsdale Jewelers'),
  ('Hobbs Jewelers'),
  ('Hodges Jewelers - MICHIGAN'),
  ('Hodges Jewelry Co. - Pelham'),
  ('Hodges Jewelry Company - Camilla'),
  ('Hoff Jewelers Inc.'),
  ('Hogan''s Jewelers'),
  ('Hogue''s Jewelry Inc.'),
  ('Holland''s Jewelers Inc.'),
  ('Holliday Jewelry'),
  ('Hollingsworth Jewelers Gallery'),
  ('Hollis & Company Jewelers - LA'),
  ('Holly McHone Jewelers - Oregon'),
  ('Holly''s Jewelry - Arkansas'),
  ('Holstrom''s'),
  ('Holt''s Jewelry - W'),
  ('Hometown Jewelers'),
  ('Honeycutt Jewelers'),
  ('Hoover Jewelers - KS'),
  ('Hoover''s Jewelers - TN'),
  ('Hope Jewelers'),
  ('Horlacher Jewelers, Inc.'),
  ('Horne Custom Jewelry'),
  ('House Of Stones'),
  ('Howard''s - NE'),
  ('Howards - GA'),
  ('Howes & Howes, Inc.-MN'),
  ('Hoyal Jewelry'),
  ('Hudson - Poole Jewelers Inc.'),
  ('Hudson Jewelers Inc.- Ohio'),
  ('Hudson Valley Goldsmith, Ltd.'),
  ('Hugh''s Jewelers - Colorado'),
  ('Hughes Jewelers - Alabama'),
  ('Hunn Co., Inc., Thomas-CO'),
  ('Hunn Jewelers Inc., Robert-MO'),
  ('Huntington Fine Jewelers'),
  ('Huntington Fine Jewelers - Shawnee'),
  ('Hupp Jewelers'),
  ('Hustedt Jewelers'),
  ('Hutcherson Jewelry, Inc'),
  ('I.M. Jewelers'),
  ('Image Jewelry Group, Inc.'),
  ('Imperial Jewelers'),
  ('Infinger''s Jewelry'),
  ('Infinity Custom Jewelers, LLC -Gahanna'),
  ('Innovative Custom Jewelry'),
  ('Intrigue Jewelers'),
  ('Iroff and Son Jewelers'),
  ('J David Jewelry - 101st Street'),
  ('J David Jewelry - Peoria Ave'),
  ('J David Jewelry- Broken Arrow'),
  ('J Jay Walsh Jewelers'),
  ('J L Winters Jewelers'),
  ('J Mullins Jewelry & Gifts'),
  ('J Tabor Jewelers'),
  ('J. A. Jewelers & Co'),
  ('J. F. Kruse Jewelers'),
  ('J. Foster Jewelers'),
  ('J. Parkerson Jewelers - MS'),
  ('J. Thomas Jewelers - MI'),
  ('J. West Jewelers'),
  ('J.C. Grant Company'),
  ('J.R. Fox Jewelers - IN'),
  ('JC Jewelers'),
  ('JJ Jewelers'),
  ('JMR Jewelers'),
  ('JR Dunn Jewelers - NC'),
  ('JR Hofstetter, The Family Jeweler'),
  ('Jackson Diamond Jewelry-OK'),
  ('Jackson Jewelry, M.E.-IL'),
  ('Jacob Matthew Jewelers Inc.'),
  ('James & Sons Fine Jewelers'),
  ('James Gattas Jewelers'),
  ('James Martin Jewelers'),
  ('James Wolf Jewelers'),
  ('Jandron''s Fine Jlry. Inc.'),
  ('Jay Flaming Jewelers'),
  ('Jay''s Jewelry'),
  ('Jayson Jewelers, Inc.'),
  ('Jeff Dennis Jewelers'),
  ('Jefferson Estate Jewelers'),
  ('Jeffrey Jewelry, Inc.'),
  ('Jerry''s Jewelers'),
  ('Jewel Art, LLC'),
  ('Jewel in the Sea'),
  ('Jeweler''s Bench, LLC -TN'),
  ('Jeweler, The- Excelsior'),
  ('Jewelers Workshop Inc.'),
  ('Jewelry Artisans - Atlanta'),
  ('Jewelry Box of Lakeland, The'),
  ('Jewelry Connection (The) -MO'),
  ('Jewelry Connection - TX'),
  ('Jewelry Design Center - Kennewick'),
  ('Jewelry Design Center - Missoula'),
  ('Jewelry Design Center - Spokane'),
  ('Jewelry Design Gallery - NJ'),
  ('Jewelry Doctors'),
  ('Jewelry Emporium, The- TN'),
  ('Jewelry Expressions Inc.'),
  ('Jewelry Shop, The - WI DBA Beth''s Jewelry Shop'),
  ('Jewelry Source, The'),
  ('Jewelry Station, Inc. (The)'),
  ('Jewelry Vault, The'),
  ('Jewelry Works - Minnetonka'),
  ('Jewels By Design'),
  ('Jim Bartlett Fine Jewelry'),
  ('Jim''s Gems-MO'),
  ('Jim''s Jewelers, Inc.-TX'),
  ('Jo & Co Jewelers'),
  ('Joe Tonos Jewelers, Inc.'),
  ('John Atencio'),
  ('John Brasfield Jewelers - COVINGTON'),
  ('John Thomas Jewelers - NM'),
  ('John''s Jewelry LTD.-KS'),
  ('Johnson Jewelers Inc. - AL'),
  ('Johnson Jewelry-MN'),
  ('Johnson the Jeweler-AR'),
  ('Johnson''s Fine Jewelry, J.L.-IN'),
  ('Johnson, Co., Inc.- NE'),
  ('Johnston Jewelers - IL'),
  ('Jon''s Fine Jewelry - FL'),
  ('Jonathan''s Jewelry - Utah'),
  ('Jones Jeweler - Ohio'),
  ('Jones Jewelers, J.F.  -  NY'),
  ('Jordan Jewelers'),
  ('Joseph Jewelers - GA'),
  ('Joseph Jewelers, LLC - CT'),
  ('Joseph''s Jewelry-WA'),
  ('Josephs Jewelers-IA'),
  ('Judith Arnell Jewelers'),
  ('Julee''s Jewelry-MN'),
  ('Julie''s Jewels & Gifts-SC'),
  ('Juniper Gem Co.'),
  ('Just For You Jewelry & Gifts'),
  ('Justin''s Watch and Jewelry Shop'),
  ('K. Hollis Jewelers - IL'),
  ('K. Westphal Jewelers - Andover'),
  ('KT Diamond Jewelers'),
  ('Karadema Inc'),
  ('Karen''s Jewelers Inc'),
  ('Karlise Fine Jewelers'),
  ('Karrow Jewelers'),
  ('Kay Cameron Jewelers'),
  ('Keenan Jewelers - K'),
  ('Keleher''s Jewelry, Inc.'),
  ('Kelley Jewelers'),
  ('Ken Walker Jewelers'),
  ('Kensington Jewelers, Inc'),
  ('Kent Island Jewelry'),
  ('Kent McKenzie Jewelers Inc'),
  ('Kevin Schimke Jewelers'),
  ('Khan Diamonds'),
  ('Kiefer Jewelers'),
  ('Kiger Fine Jewelers'),
  ('Kim''s Fine Jewelry'),
  ('Kimberly-Scott Creations'),
  ('King''s Jewelry - VA'),
  ('Kingston Fine Jewelry'),
  ('Kirk & Company Jewelers'),
  ('Klug''s Country Gold Ltd.'),
  ('Kluh Jewelers, G.L.- Lacey'),
  ('Kluh Jewelers, S.T.'),
  ('Koerber''s Fine Jewelry'),
  ('Komara Jewelers'),
  ('Koser Jewelers'),
  ('Kottke Fine Jewelers, Laurie - M'),
  ('Kottke Jewelers - Owatonna'),
  ('Krekeler Jewelers, Inc.-O''Fal'),
  ('Krekeler Jewelers-Frm'),
  ('Krueger Jewelers - WI'),
  ('Kuhns  Jewelers'),
  ('Kux Jewelers'),
  ('LR Jewelers, Inc.'),
  ('LaBiche Jewelers, LLC'),
  ('LaDon''s Fine Jewelry LLC'),
  ('LaGene Jewelers Inc.'),
  ('Laiti Jewelers - H'),
  ('Lake Oswego Jewelers'),
  ('Lambert Jewelers'),
  ('Landis Jewelers E.G.'),
  ('Lara''s Jewelry and Design'),
  ('Lasker''s Inc.-WI'),
  ('Laudick''s Jewelry, LLC - Van Wert'),
  ('Lauhoff Jewelry & Gifts LLC - C'),
  ('Laura Stanley Personal Jeweler'),
  ('Lauray''s The Diamond Center'),
  ('Lawrence Jewelers'),
  ('Layne''s Jewelry'),
  ('LeRAVe Jewelry'),
  ('Lee Ann''s Fine Jewelry - Conway'),
  ('Lee Ann''s Fine Jewelry Inc. - Russellville'),
  ('Lee Jeweler, AM'),
  ('Legacy Diamond & Gems'),
  ('Legend Jewelers'),
  ('Leibrandt Jewelry Store LLC'),
  ('Leitzel''s Jewelry'),
  ('Leo''s Jewelry & Gifts - MI'),
  ('Leo''s Jewelry - NE'),
  ('Lester Martin Jewelers'),
  ('Linds'),
  ('Liria Gift & Jewelry, Inc'),
  ('Little Gold Mine (The)'),
  ('Little Treasury Jewelers'),
  ('Little''s Jewelers - Corinth'),
  ('Little''s Jewelers - Tupelo'),
  ('Lizzy''s Jewelry/Marysville Pawn'),
  ('Loch Jewelers, Inc.'),
  ('Lodan Design Studio Inc.'),
  ('Long Jewelers III - Chesapeake'),
  ('Long Jewelers, Inc - Virginia Beach'),
  ('Loreena Rose Jewelry'),
  ('Luckey''s Jewelers'),
  ('Luisa Graff Jewelers'),
  ('Luttrell Jewelers'),
  ('Lyla Jewelers'),
  ('M.K. Benatti Jewelers Inc.'),
  ('MARBILL Diamonds and Jewelry'),
  ('MPC Jewelry Design, Inc'),
  ('Madison Avenue Jewelry & Gfts - SC'),
  ('Main Street Jewelry, Inc.'),
  ('Mainland Pawn & Jewelry - TX'),
  ('Maitland Jewelers - FL'),
  ('Makepeace Jewelers'),
  ('Malashock''s Jewelry'),
  ('Mallory''s Creations'),
  ('Malsons Jewelers - 86th Street'),
  ('Malsons Jewelers - Kings Plaza'),
  ('Mann''s Jewelers Inc.'),
  ('Mansour Jewelers'),
  ('Marion''s Jewelry, Inc.'),
  ('Mark Jewellers Inc.-WI'),
  ('Mark Loren Designs'),
  ('Marks Jewelers - Kansas'),
  ('Marks Jewelry - IA'),
  ('Marks of Design, LLC-CT'),
  ('Marlyn Jewelers Inc'),
  ('Marquirette''s Exquisite Jewelry'),
  ('Marthaler Jewelers Inc'),
  ('Martin Jewellers - Shawano'),
  ('Martinique Jewelers'),
  ('Mason Jewelers (Greencastle)'),
  ('Mason Jewelers (Plainfield)'),
  ('Massey Jewelers'),
  ('Master Jewelers'),
  ('Mauk Jewelers Inc.'),
  ('Mauzie''s Fine Jewelry'),
  ('McFerrin''s Jewelry'),
  ('McIntosh Jewelry Inc'),
  ('McKay Jewelers'),
  ('McKenzie and Smiley Jewelers'),
  ('Meadows'' Jewelers'),
  ('Mees Jewelry'),
  ('Mehaffey''s Jewelry'),
  ('Meigs Jewelry'),
  ('Melan Expressions LLC'),
  ('Melancon Jewelers'),
  ('Melby''s Jewelers'),
  ('Melgram Jewelers Inc'),
  ('Melody''s Quality Jewelry'),
  ('Menk  Jewelers, Inc., E.L.'),
  ('Michael & Son''s - NV'),
  ('Michael Eller Diamonds - F'),
  ('Michael Szwed Jewelers'),
  ('Michael''s Creative Jewelry - Phoenix'),
  ('Michael''s Fine Jewelry & Gifts, Inc-LA'),
  ('Michael''s Jewelry - NC'),
  ('Michael''s Reflections in Gold - FL'),
  ('Michele & Company Fine Jewelers -MI'),
  ('Michele Jewelry, Inc. - Texas'),
  ('Mike Wright Jewelers'),
  ('Milano Jewelers'),
  ('Milkins - Monroe'),
  ('Milkins Jewelers - Wyandotte'),
  ('Miller Jewelers, Alan-OH'),
  ('Miller''s Fine Jewelers -WA'),
  ('Miller''s Fine Jewelry, Inc. - MO'),
  ('Miller''s Jewelry - MN'),
  ('Mills Jewelers Inc - NY'),
  ('Minglin Jewelers'),
  ('Miska Jewelers'),
  ('Mississippi Diamond Jewelers'),
  ('Mitchell''s Jewelry (Norman)'),
  ('Mitchener Farrand Fine Jewelry'),
  ('Mitchum Jewelers Inc.'),
  ('Moeller, R.F. Ltd'),
  ('Molinelli''s Jewelers'),
  ('Mon Amie Fine Jewelry'),
  ('Moore Jewelers - TX'),
  ('Moore''s Jewelers, Inc. - MS'),
  ('Morgan''s Jewelers - MN'),
  ('Morning Star Jewelers, Inc.'),
  ('Morris Jewelers - NC'),
  ('Morris Jewelry - KY'),
  ('Morrissey''s Fine Jewelry'),
  ('Moses Jewelers - PA'),
  ('Motif Jewelers'),
  ('Mucklow''s Fine Jewelry'),
  ('Mullen Bros.'),
  ('MurDuff''s, Inc.'),
  ('Murphy Pitard Jewelers'),
  ('Murphy''s Jewelers, Inc. - Magnolia'),
  ('My Jeweler'),
  ('Nacol''s Jewelry'),
  ('Nancy & Co. Fine Jewelers'),
  ('National Jewelry Company'),
  ('Nature Coast Goldsmith Jewelers Inc.'),
  ('Necker Jewelry'),
  ('Neece Jewelers,Inc'),
  ('Needham Jewelers, SE, Inc.'),
  ('Neeter House of Luxury'),
  ('Nelsen''s Fine Jewelry, Inc. - CO'),
  ('Nelson Jewelry'),
  ('Nelson''s Jewelry - Crystal Lake'),
  ('Neugebauer''s Fine Jewelry'),
  ('Niche of Time Jewelry'),
  ('Nick T. Arnold Jewelers, Inc.'),
  ('Noble Jewelers'),
  ('Noe''s Jewelry'),
  ('Nummi Jewelers'),
  ('Nyman Jewelers, Inc.'),
  ('OJB Jewelry, LLC (Eli''s)'),
  ('Oak Valley Jewelers - Oakdale, CA'),
  ('Oaks Jewelers - Berkeley, CA'),
  ('Occasions Fine Jewelry'),
  ('Ocean View Jewelers'),
  ('Oden Watches and Jewelry'),
  ('Old San Juan Jewelers Inc.(The)'),
  ('OldeTowne Jewelers - W'),
  ('Omega Diamond Jewelers'),
  ('Orange City Watch & Jewelry Repair, Inc'),
  ('Orin Jewelers'),
  ('Osborne Jewelers - Goodyear'),
  ('Osborne''s Jewelers - H'),
  ('Osborne''s Jewelers Inc.-A'),
  ('Oz''s Jewelers'),
  ('P.R. Sturgill Fine Jewelry'),
  ('Pace Jewelers, Inc.'),
  ('Pacheco''s Jewelry & Gifts'),
  ('Padgetts Jewelry'),
  ('Pagan''s Jewelry, Inc'),
  ('Palazzo Jewelers'),
  ('Palmer''s Jewelry Inc'),
  ('Pamela''s Fine Jewelry'),
  ('Panowicz Jewelers'),
  ('Park Place Jewelers - Ocean City'),
  ('Parker Jewelers - PA'),
  ('Parker Jewelers- MI'),
  ('Parkers Karat Patch - NC'),
  ('Parks Diamond Jewelers, Inc-TX'),
  ('Parkville Jewelers LLC - MO'),
  ('Parris Jewelers, LLC - MS'),
  ('Pat''s Jewelry Centre, LTD-IA'),
  ('Patina Jewelry + Design'),
  ('Paul Bensel Jewelers'),
  ('Pauls Jewelry Designs'),
  ('Payne Anthony Creative Jewelers'),
  ('Pentaltha, Inc.'),
  ('Perry Jewelers, H., Inc.'),
  ('Perry''s Diamonds & Estate Jewelry - Charlotte'),
  ('Perry''s Emporium Inc.- Wilmington/Shalotte/Hampstead'),
  ('Peter Franklin Jewelers'),
  ('Pettit Jewelers'),
  ('Pharaoh''s Jewelers LLC'),
  ('Phil Jewelers - SC'),
  ('Philip''s Diamond Shop - Marion'),
  ('Pickens, Inc. Jewelers'),
  ('Pickett Brothers Jewelers'),
  ('Pierce Custom Jewelers - FL'),
  ('Pierce Jewelers - IN'),
  ('Piette Jewelers Inc - MA'),
  ('Pineforest Jewelry'),
  ('Piper Diamond Co.'),
  ('Pittman Jewelers'),
  ('Plantation Jewelers Inc.'),
  ('Plateau Jewelers, Inc. - WA'),
  ('Plaza Jewelers -WA'),
  ('Potter''s Jewelry'),
  ('Powell Jewelry'),
  ('Powers & Son Jewelers-TN'),
  ('Prestige Jewelers, Inc. - Hiram'),
  ('Price''s- Minnesota'),
  ('Puckett''s Fine Jewelry - Benton'),
  ('Puckett''s Fine Jewelry - Murray'),
  ('Pugh''s Designer Jewelers - Newark'),
  ('Quality Jewelers - ME'),
  ('Quenan''s Jewelers'),
  ('Quinn''s Diamond Jewelers - SC'),
  ('Quinn''s Goldsmith - Virginia'),
  ('Quinn''s Jewelry Inc. - R'),
  ('R Bruce Carson, Ltd'),
  ('R Gregory Jewelers - Statesville'),
  ('R. Thomas Jewelers'),
  ('R. Westphal Jewelers (Hutchinson)'),
  ('R.J. Jewelers - NY'),
  ('R.M. Johnson & Sons Jewelers'),
  ('RC Wahl Jewelers'),
  ('RN Jewelers'),
  ('Rae''s Jewelry, Inc.'),
  ('Raleigh Diamond Fine Jewelry'),
  ('Randy Arnett Jewelers'),
  ('Randy''s Jewelry, Inc'),
  ('Raskin''s Jewelers'),
  ('Rasmussen Diamonds'),
  ('Rauchs Jewelry Inc -Newton'),
  ('Rawls Jewelers'),
  ('Ray Harp Jewelers'),
  ('Ray Jewelers - NY'),
  ('Ray, Max Jewelers'),
  ('Rebel Diamonds'),
  ('Reck Jewelers, Carl V., Inc.'),
  ('Redlands Jewelers'),
  ('Reed & Sons Jewelers'),
  ('Rees Jewelry LLC'),
  ('Reigning Jewels Fine Jewelry - TX'),
  ('Reiniger Jewelers - Alton'),
  ('Reiniger Jewelers - Ballwin'),
  ('Reiniger Jewelers - Effingham'),
  ('Reiniger Jewelers - Swansea'),
  ('Reiniger Jewelers - Waterloo'),
  ('Renee Taylor Gallery'),
  ('Reusch Jewelers'),
  ('Richard''s Jewelry - Indiana'),
  ('Richter & Phillips Co.'),
  ('Rickie David Jewelers'),
  ('Rihners Jewelers LLC'),
  ('Riley-White Drugs'),
  ('Rinehart Jewelry'),
  ('Ritter Brothers Jewelry & Repair'),
  ('Ritzi Jewelers'),
  ('Robert K. Grant'),
  ('Robert''s Jewelers - Jackson'),
  ('Robert''s Jewelers Inc - SC'),
  ('Roberts Jewelers - Del Rio'),
  ('Roberts Jewelers - Meadville'),
  ('Robichau''s Jewelry'),
  ('Robinette Jewelers - Seneca Falls'),
  ('Robins Jewelry- Collierville'),
  ('Robinson Family Jewelers -Cortland'),
  ('Robson''s Diamond Jewelers - TX'),
  ('Rochester Lapidary Jewelers'),
  ('Rogers Fine Jewelers - TX'),
  ('Rogers Jewelers, Inc. - MI'),
  ('Rogers Jewelry - MA'),
  ('Roman Jewelers'),
  ('Romanation Jewelers'),
  ('Rome Jewelers - Lebanon'),
  ('Rome Jewelers - Xenia'),
  ('Rome Jewelers -Wilmington'),
  ('Rome Jewelers-Hillsboro'),
  ('Roof Jewelers & Awards'),
  ('Root Jewelers'),
  ('Rose Jewelers'),
  ('Rosenfeld Jewelry LTD'),
  ('Ross Elliott Jewelers'),
  ('Ross''s Fine Jewelers'),
  ('Rosson Company'),
  ('Roth Jewelers'),
  ('Rox Jewelers'),
  ('Roy''s Jewelry Store'),
  ('Royal Diadem Jewelers'),
  ('Royal Fine Jewelers - KY'),
  ('Royal Jewelers-IA'),
  ('Ruby Jewelry Co, Inc'),
  ('Runyan''s Jewelers'),
  ('Ruppelius Jewelers'),
  ('Russakoff Jewelers'),
  ('S&E Jewelers - New York'),
  ('SJ Custom Jewelers'),
  ('SVS Fine Jewelry'),
  ('Saginaw Gold & Diamond Center'),
  ('Salem''s Jewelry - Marble Falls'),
  ('Salem''s Jewelry -Burnet'),
  ('Sam Dial Jewelers'),
  ('Sam''s Fine Jewelry - MO'),
  ('Sami Fine Jewelry - AZ'),
  ('Sanborn''s Jewelers'),
  ('Sanders Diamond Jewelers -MD'),
  ('Sanders Jewelry - AL'),
  ('Sartor Hamann Jewelers'),
  ('Sasso'),
  ('Sather Jewelry - WI'),
  ('Sather''s Leading Jewelers, Inc-CO'),
  ('Sawyer Jewelers, Inc.'),
  ('Saxon''s Diamond Centers - Aberdeen'),
  ('Saxon''s Diamond Centers - Bel Air'),
  ('Saxon''s Fine Jewelers - Oregon'),
  ('Sayers Jewelers & Gemologists'),
  ('Schmitt Jewelers - AZ'),
  ('Schwartz Jewelers - C'),
  ('Scott and Sons Fine Jewelry'),
  ('Seever''s Jewelers, LLC'),
  ('Segner''s Jewelers'),
  ('Seibert - House of Gems by J. Seibert'),
  ('Seifert Jewelry'),
  ('Seita Jewelers'),
  ('Select Jewelers'),
  ('Selman''s Jewelers - Gemologists, Inc.'),
  ('Servinsky Jewelers'),
  ('Setterberg Jewelers - AZ'),
  ('Setterberg Jewelers - MN'),
  ('Seven Oaks Fine Jewelers'),
  ('Shains of Lumberton'),
  ('Shannon Fine Jewelry - W'),
  ('Shay''s Jewelers'),
  ('Shelia Bayes Jewelers'),
  ('Shelle Jewelers'),
  ('Shipley''s Fine Jewelry'),
  ('Sickinger''s Jewelry'),
  ('Sierra Moon'),
  ('Signature Jewelers'),
  ('Simons & Son, George'),
  ('Skaneateles Jewelry Inc'),
  ('Skatell''s Jewelers'),
  ('Skewes Jewelry Inc.'),
  ('Sky Diamond Jewelers'),
  ('Smith Jewelers - AL'),
  ('Smith Jewelers Inc. - VA'),
  ('Smith''s of Dublin'),
  ('Snider''s Jewelers Inc. - PA'),
  ('Snyder Jewelers - CO'),
  ('Sohn and McClure Jewelers - Bay Street'),
  ('Sophia''s Jewelry Studio, Ltd.'),
  ('South Miami Jewelers'),
  ('Sovell Jewelry'),
  ('Spalding Jewelry'),
  ('Sparkles Jewelry'),
  ('Spath Jewelers - B'),
  ('Spath Jewelers - V'),
  ('Springer''s Jewelers'),
  ('Spritz Jewelers'),
  ('St John''s Jewelers - Ellicott City'),
  ('Staats Jewelers'),
  ('Stadheim Jewelers of Mason City'),
  ('Stadheim''s - Albert Lea'),
  ('Stall and Kessler''s'),
  ('Stambaugh Jewelers'),
  ('Stark, C.B.'),
  ('State St. Jewelers -NC'),
  ('State Street Jewelers - IL'),
  ('Sterling Jewelers of Connecticut, Inc.'),
  ('Steve Pronko Jewelers'),
  ('Steve''s Jewelry - LA'),
  ('Steven Christopher Jewelers'),
  ('Stockhill Jewelers - Sidn, John'),
  ('Stokes Jewelry'),
  ('Stones Jewelry - W'),
  ('Storey Jewelers'),
  ('Sturhahn Jewelers, Inc. - MO'),
  ('Sturhahn Jewelers-IL'),
  ('Sugar Plum Jewelry Co.'),
  ('Sullivan''s Jewelers, Inc'),
  ('Summerlin Jewelers'),
  ('Sunshine Goldmine'),
  ('Sutton Jewelry'),
  ('Swedes Jewelers'),
  ('Sweet Custom Jewelry'),
  ('Sycamore Jewelers'),
  ('T. Simon Jewelers'),
  ('TTOG'),
  ('Tammy''s Jewelry'),
  ('Tanco Creations'),
  ('Tara & Co. Fine Diamonds'),
  ('Tatge Jewelry - K'),
  ('Taylor Made Jewelry, Inc. - OH'),
  ('Tena''s Jewelry & Gift Shop-E'),
  ('Tenenbaum''s Jewelry'),
  ('Tennie''s Jewelry'),
  ('Texas Gold Connection'),
  ('Thacker Jewelry'),
  ('The Diamond Shop - MISSOURI'),
  ('The Diamond Studio- OH'),
  ('Thollot Diamonds & Fine Jewelry'),
  ('Thomas Jewelers - PA'),
  ('Thomason Jewelers (Earl)-SC'),
  ('Thompson Jewelers - FL'),
  ('Thompson Jewelers-TN'),
  ('Thompson Jewelry, Ken K..-MN'),
  ('Thompson''s Jewelry - AR'),
  ('Thurber''s Jewelry, Inc'),
  ('Tidewater Gold & Diamond'),
  ('Tidwell Jewelers of Greenwood'),
  ('Tidwell Jewelers-Johnston'),
  ('Tillis Jewelry - C'),
  ('Timmreck and McNicol Jewelers'),
  ('Tipton''s Fine Jewelry'),
  ('Tobin Jewelers - Mequon'),
  ('Tobin Jewelers - New Berlin'),
  ('Todd''s Jewelry Repair and Design, LLC'),
  ('Touch of Class Jewelers'),
  ('Towne Square Jewelers LLC-IL'),
  ('Traditions Fine Jewelers'),
  ('Treasure''s Fine Jewelry LLC-IOWA'),
  ('Treasure''s Jewelers - Tennessee'),
  ('Trinity Jewelers - PA'),
  ('Trinkets'),
  ('Tripp & Company Jewelers'),
  ('Turner''s Jewelers, Inc.'),
  ('US Gold Jewelers'),
  ('UniQ Jewelry Gallery'),
  ('Utiger Jewelry, Inc.'),
  ('Vail Creek Jewelry Designs'),
  ('Valentine''s Jewelry LLC'),
  ('Valia''s Jewelers'),
  ('Valle Jewelers - NY'),
  ('Van Denover Jewelry, Inc'),
  ('Van Drake Jewelers'),
  ('Van Duzer Jewelers'),
  ('Van Gundy Jewelers'),
  ('Van Horn Jewelers'),
  ('Vanessa Fine Jewelry'),
  ('Vashti''s Inc'),
  ('Vaughan''s Jewelry & Fine Gifts'),
  ('Vecere Jewelers'),
  ('Venus Jewelers and Gemologists'),
  ('Victoria Marie Jewelers, Inc'),
  ('Vincent J. Jewelers'),
  ('Von''s Inc. - L'),
  ('W.P. Shelton Jewelers'),
  ('Waddington Jewelers'),
  ('Walkers n'' Daughters Jewelers.-ND'),
  ('Walsons & Co.'),
  ('Walter''s Jewelers'),
  ('Walton''s Jewelry'),
  ('Waterfall Jewelers - Wtr'),
  ('Waterfall Jewelers II - W Lake'),
  ('Weber Brothers'),
  ('Weber Jewelry & Gifts -Robinson'),
  ('Weber''s Jewelry - Teutopolis'),
  ('Weber, Raimie H., LLC'),
  ('Weiss Jewelers'),
  ('Welling & Co.'),
  ('Welsh International'),
  ('Wendel''s Diamond Jewelers'),
  ('West End Jewelers'),
  ('Westphal Jewelers, D (Bradley)'),
  ('Wetzel &Truex Jewelers'),
  ('Wexford Jewelers'),
  ('Whidby Jewelers'),
  ('White''s Fine Jewelry'),
  ('Wickersham Jewelry, Inc.'),
  ('Wiersema Jewelry'),
  ('Wiggins'' Jewelers'),
  ('Wild Mountain Fine Jewelers'),
  ('Wild Wood Custom Jewelry'),
  ('Wiley''s Diamonds & Fine Jewelry'),
  ('Wilkerson Jewelers-S'),
  ('William Howard''s Jewelers, Inc.-FL'),
  ('William Williams Rare Jewels'),
  ('Williams Diamond Center - MN'),
  ('Willow Glen Diamond Co'),
  ('Wimmer''s Diamonds'),
  ('Windham Jewelers'),
  ('Windle''s Rock & Jewelry'),
  ('Windmill Park Jewelers'),
  ('Wingo''s Fine Jewelry'),
  ('Wink''s Fine Jewelry'),
  ('Wirt''s Jewelers'),
  ('Witt''s Jewelry'),
  ('Woelk''s House of Diamonds, LLC'),
  ('Wolf & Stag Fine Jewelry'),
  ('Wolf Fine Jewelers - Atlantic City'),
  ('Wolf Fine Jewelers - Middletown'),
  ('Woody''s Jewelry'),
  ('Worthington Jewelers'),
  ('Wright''s Jewelry Store - Fallston'),
  ('Wyatts Diamond Jewelers - Monroe'),
  ('Yanko Jewelers Inc'),
  ('Yates & Co Jewelers, Inc'),
  ('York Jewelers'),
  ('Your Jeweler - ILLINOIS'),
  ('Your Jewelry Box, LLC - PENNSYLVANIA'),
  ('Your Private Jeweler of Lake Norman'),
  ('Z''s Fine Jewelry -AZ'),
  ('Zalman''s Treasures'),
  ('Zembar Jewelers'),
  ('Zimbelman''s Jewelry')
),
-- Normalize both sides identically.
rjo_norm AS (
  SELECT name AS raw,
         LOWER(BTRIM(
           REGEXP_REPLACE(
             REGEXP_REPLACE(
               REGEXP_REPLACE(name, '[''.,]', '', 'g'),
               E'\\s+(inc|llc|ltd|co|company)\\.?$', '', 'i'),
             E'\\s+-\\s*.{1,40}$', '', 'i')
         )) AS norm
  FROM rjo_raw
),
stores_norm AS (
  SELECT id, name AS raw,
         LOWER(BTRIM(
           REGEXP_REPLACE(
             REGEXP_REPLACE(
               REGEXP_REPLACE(name, '[''.,]', '', 'g'),
               E'\\s+(inc|llc|ltd|co|company)\\.?$', '', 'i'),
             E'\\s+-\\s*.{1,40}$', '', 'i')
         )) AS norm
  FROM public.trunk_show_stores
),
-- Best (highest-similarity) RJO match per trunk store, threshold 0.30.
best_match AS (
  SELECT DISTINCT ON (s.id)
    s.id            AS store_id,
    s.raw           AS store_name,
    n.raw           AS rjo_name,
    similarity(s.norm, n.norm) AS sim
  FROM stores_norm s
  CROSS JOIN rjo_norm n
  WHERE similarity(s.norm, n.norm) >= 0.30
  ORDER BY s.id, similarity(s.norm, n.norm) DESC, n.raw
)
INSERT INTO public.store_trade_organization_members (store_id, org_id)
SELECT b.store_id, o.id
FROM best_match b
CROSS JOIN public.trade_organizations o
WHERE o.name = 'RJO'
ON CONFLICT (store_id, org_id) DO NOTHING;

-- Stats notice
DO $$
DECLARE total_count BIGINT; tagged_count BIGINT;
BEGIN
  SELECT COUNT(*) INTO total_count FROM public.trunk_show_stores;
  SELECT COUNT(*) INTO tagged_count
    FROM public.store_trade_organization_members m
    JOIN public.trade_organizations o ON o.id = m.org_id
    WHERE o.name = 'RJO';
  RAISE NOTICE 'Tagged % of % trunk_show_stores rows as RJO members.', tagged_count, total_count;
END $$;

-- Audit report — every trunk_show_store + its current RJO tag status
-- + the best-similarity RJO match it had (even if below threshold).
-- Useful for spot-checking false positives and hand-tagging anything
-- the algorithm missed.
WITH
rjo_raw(name) AS (
  VALUES
  ('5th Avenue Jewelers'),
  ('A & J Jewelers'),
  ('A. L. Terry Jewelers'),
  ('ART Jewelers'),
  ('AZ Fine Jewelry and Repair'),
  ('Abby''s Gold and Gems'),
  ('Abernathy Fine Jewelers'),
  ('Ace of Diamonds'),
  ('Adams Jewelers VA NC'),
  ('Adler''s Diamonds'),
  ('Alan Sutton Jewelry'),
  ('Albert''s Diamond Jewelers - IN'),
  ('Albert''s Jewelers, Inc.- GA'),
  ('Albert''s Jewelry & Awards - ME'),
  ('Alexander Fine Jewelers - MI'),
  ('Alexander''s Jewelry - PA'),
  ('Alicia Fine Jewelers'),
  ('Allain''s Jewelry & Trophy Shop Inc.'),
  ('Allan Jewelers - Shenango Rd.'),
  ('Allan Jewelers -3rd St.'),
  ('Allen''s Fine Jewelry - Winona'),
  ('Allen''s Fine Jewelry- Grenada'),
  ('Allen''s Jewelers- Jacksonville'),
  ('Allison''s Fine Jewelry'),
  ('Alpine Jewelers'),
  ('Altemueller Jewelry'),
  ('Ambassador Diamond Jewelers'),
  ('Amber''s Designs'),
  ('Amor Fine Jewelry - NY'),
  ('Amore'' Jewelers - FL'),
  ('Amos Jewelry'),
  ('Amy & Co. Fine Jewelry'),
  ('Anderson Jewelry- Minden'),
  ('Anderson''s Jewelry - Effingham'),
  ('Anderson''s Jewelry - Yazoo City'),
  ('Andersons Diamond Jewelers - SC'),
  ('Andrew Z Diamonds -  Anthem'),
  ('Andrew Z Diamonds - Carefree'),
  ('Andrew Z Diamonds - Scottsdale'),
  ('Andy''s Jewelry  - Lafayette'),
  ('Anfesa''s Jewelers, Inc'),
  ('Ann Booth Jewelers'),
  ('Annapolis Jewelers'),
  ('Anne-Marie''s Fine Jewelry'),
  ('Anthony Jewelers'),
  ('Apland Jewelers'),
  ('Armbruster Jewelers'),
  ('Arnett''s Fine Jewelry'),
  ('Arney Guess Goldsmith'),
  ('Arthur''s Jewelry'),
  ('Ashland City Jewelers & Pawn'),
  ('Asmar Jewelz'),
  ('Aspen Jewelry Designs, Inc'),
  ('Atchison''s Jewelry'),
  ('Aurora Jewelers'),
  ('Avitabile Fine Jewelers'),
  ('Avonlea Jewelers LLC'),
  ('Ayers Jewelers Co. (Lee) - WI'),
  ('B & L Jewelers'),
  ('B&E Jewelers & Gemologists'),
  ('Bachman Jewelers, Inc'),
  ('Bacon Jewelers'),
  ('Bailey''s Jewelers'),
  ('Baker & Baker - OH'),
  ('Baker''s Jewelry - IL'),
  ('Baker''s Jewelry, Inc. - MT'),
  ('Balefire Goods'),
  ('Ballard & Ballard Jewelers'),
  ('Banks Jewelers - NC'),
  ('Barnes Diamonds & Designs - WI'),
  ('Barnes Fine Jewelers, Inc. - AZ'),
  ('Barnett Jewelers'),
  ('Barnhardt Jewelers, Inc'),
  ('Barry Coats Jewelers - Livingston'),
  ('Bartelsmeyer Jewelry'),
  ('Basch Jewelers, Inc. (Don)-Mac'),
  ('Basch''s Moment in Time-N Olmst'),
  ('Bauble Patch Jewelers'),
  ('Bauer Jewelers & Gemologists, Inc.-IN'),
  ('Bauer''s Jewelry Inc. - MICHIGAN'),
  ('Bay Area Diamond Co., LLC'),
  ('Bay Street Jewelers, Inc. - SC'),
  ('Bayside Coin & Jewelry - WA'),
  ('Bea''s Jewelers'),
  ('Becker Jewelers - IL'),
  ('Becker''s Jewelers, Inc. - IA'),
  ('Beeghly & Co. Jewelers & Gemologists-G'),
  ('Beeghly & Keim Jewelers & Gemologists-S'),
  ('Bell Jewelers - TN'),
  ('Bella Cosa Jewelers-IL'),
  ('Bella Design Jewelers - Chagrin Falls'),
  ('Bella Jule Fine Jewelry'),
  ('Bellman Jewelers'),
  ('Ben David Jewelers'),
  ('Bennion Jewelers'),
  ('Benqueil''s Jewelry, Inc.'),
  ('Berg Jewelry'),
  ('Bergey Jewelry - MH'),
  ('Bergey Jewelry- Oregon'),
  ('Berilian Jewelers'),
  ('Bethany''s Jewelry and Design'),
  ('Better Bling Studio'),
  ('Bichsel Jewelry'),
  ('Big Ben Jewelers'),
  ('Bill French Jewelers, LLC'),
  ('Bits of Gold Jewelry & Gifts'),
  ('Blackmon''s Jewelry Repair & Mfg.'),
  ('Blanchard Jewelers, Gary'),
  ('Bland''s Jewelry LLC'),
  ('Blanquart Jewelers - B'),
  ('Blase DeNatale Jewelers'),
  ('Bling Jewelers'),
  ('Blocher Jewelers'),
  ('Blue Diamond (The)'),
  ('Blue Water Jewelers'),
  ('Bluestone Jewelry, Inc.'),
  ('Bohland Jewelers'),
  ('Boucher Jewelers'),
  ('Bowers Jewelers - H'),
  ('Bowers Jewelry - W'),
  ('Boyer''s Diamonds'),
  ('Boyle Jewelers, Inc.'),
  ('Bradley''s Jewelers Inc'),
  ('Bradow Jewelers - WI'),
  ('Bradshaw''s Jewelers'),
  ('Branham''s Jewelry'),
  ('Brax Jewelers'),
  ('Bremer Jewelry'),
  ('Bridgewater Jewelers'),
  ('Britt Jewelry - MS'),
  ('Brittany''s Fine Jewelry, Inc.'),
  ('Britton Jewelers, LTD'),
  ('Brockhaus Jewelry'),
  ('Brown Goldsmiths'),
  ('Brown Jewelry - MT'),
  ('Bryan Jewelry - Alabama'),
  ('Bryan and Son Fine Jewelers'),
  ('Buchkosky Jewelers'),
  ('Buck''s Jewelry'),
  ('Bullock''s Jewelry'),
  ('Bulow Jewelers'),
  ('Burke''s Inc'),
  ('Burnell''s Fine Jewelry and Design'),
  ('Butler & Company, K E - GA'),
  ('Butler Diamonds and Fine Jewelry - Selma'),
  ('CBC Fine Jewelers - El Paso'),
  ('CC Jewelers - Traverse City'),
  ('CDI Diamonds & Jewelry'),
  ('CMK Jewelers and Repair LLC'),
  ('CMS Fine Jewelers'),
  ('CR Diamonds & Gems'),
  ('Caesar''s Jewelers'),
  ('Cahill-Pribyl Jewelry & Gifts'),
  ('Calhoun''s Jewelers'),
  ('Cameo Jewelers'),
  ('Capper Jewelry LLC'),
  ('Caratti Jewelers, Inc.'),
  ('Carlson Brothers Jewelry -WA'),
  ('Carlson''s Jewelers - MD'),
  ('Carroll - Ochs Jewelers'),
  ('Carroll''s Jewelers'),
  ('Cartersville Jewelry Exchange'),
  ('Castle Rocks and Jewelry'),
  ('Catawba Island Jewelers'),
  ('Caves Jewelry'),
  ('Central Jewelry Company'),
  ('Champaign Jewelers'),
  ('Chapman Jewelry & Repairs, Inc.'),
  ('Chappuis'),
  ('Charland Jewelers'),
  ('Charles Lynn Jewelers'),
  ('Cheryl Burchell Goldsmiths'),
  ('Chilson Jewelers - C'),
  ('Chipper''s Jewelry'),
  ('Chrey''s Jewelry'),
  ('Christensen Jewelers LLC - Marshfield'),
  ('Christensen Jewelry - Hampton'),
  ('Christopher''s Fine Jewelry'),
  ('Cindi''s Diamond and Jewelry Gallery'),
  ('Clark Jewelers - KY'),
  ('Clark''s Diamond Jewelers - ID'),
  ('Clark''s Jewelry Store - OH'),
  ('Clarkes Jewelers - LA'),
  ('Clarkson Jewelers - MO'),
  ('Clarksville Jewelers - TN'),
  ('Classic Designs Jewelry, Inc -CA'),
  ('Classique Jewelers, Inc.-TX'),
  ('Clater Jewelers'),
  ('Cleveland Jewelers Inc./ Coats'),
  ('Cline Jewelers'),
  ('Clinton Jewelers'),
  ('Clodius & Co. Jewelers'),
  ('Clonts Jewelry'),
  ('Coastal Jewelers'),
  ('Coffin & Trout Jewelers'),
  ('Collard Jewelers'),
  ('Colonial Jewelers'),
  ('Comfort and Son Jewelers'),
  ('Cone Jewelers - NM'),
  ('Cook Jeweler, Inc(Tom) - Daytona Beach'),
  ('Cook''s Jewelry LLC - Carrollton'),
  ('Cooper & Binkley Jewelers'),
  ('Cooper''s Fine Jewelry - FL'),
  ('Corinth Jewelers - MS'),
  ('Cornerstone Jewelers -KY'),
  ('Cornerstone Jewelry and Repair - MO'),
  ('Corwin''s  Main Street Jewelers'),
  ('Cottage Hill Diamonds'),
  ('Couch''s Jewelers'),
  ('Courtyard Mfg. Jewelers, LLC'),
  ('Cowardin''s Jewelers'),
  ('Cozzi Jewelers'),
  ('Craig Husar Fine Diamonds'),
  ('Cravens & Lewis Jewelers'),
  ('Crawford''s Jewelers Inc'),
  ('Creative Jewelers - AL'),
  ('Creative Jewelers - NC'),
  ('Cresalia Jewelers'),
  ('Crescent Jewelry'),
  ('Crews Jewelry'),
  ('Crider Quality Jewelers'),
  ('Croft & Stern Jewelry Designs'),
  ('Crown Jewelers- Virginia'),
  ('Crown Jewelry, Inc. - OK'),
  ('Cryan Jewelers, John S.'),
  ('Culy''s Jewelry, LLC'),
  ('Cunningham Jewelers'),
  ('Custom Jewelry, Inc'),
  ('Cyrus Jewelers'),
  ('D&D Jewelers - IL'),
  ('D-Lux Jewelers Inc'),
  ('DJ''s Jewelry & Gift'),
  ('DK Jewelers Inc.'),
  ('Dahlkemper''s Jewelry Connection'),
  ('Dan Gould Jewelers - A'),
  ('Dan Martin Jewelers LLC'),
  ('Dannels Jewelry'),
  ('Danwerke International'),
  ('Danz Jewelers- L'),
  ('Dave Askew Jewelers, LLC'),
  ('Dave''s Jewelry'),
  ('David Charles Ltd'),
  ('David Douglas Diamonds & Jewelry'),
  ('David''s Fine Jewelry - Breux Bridge'),
  ('Davis Jeweler, Thomas A. -MI'),
  ('Davis Jewelers - GA'),
  ('DeAngelis Jewelers'),
  ('DeVries Jewelry Store'),
  ('Dean''s Jewelry'),
  ('Deep South Gold'),
  ('Del Haven Jewelers'),
  ('Dempsey''s Jewelers'),
  ('Designer''s Circle'),
  ('Designs by Aaron'),
  ('Diamond & Designs - MN'),
  ('Diamond Classics'),
  ('Diamond Design by Bodis - WI'),
  ('Diamond Designs - IL'),
  ('Diamond Direct - Brea CA'),
  ('Diamond Durrell''s'),
  ('Diamond Jewelers - AL'),
  ('Diamond Jim''s - Phoenix'),
  ('Diamond Rush - NC'),
  ('Diamond Shop, The - IDAHO'),
  ('Diamond Showcase'),
  ('Diamond Store, The -Mitchell'),
  ('Diamonds By Dawn'),
  ('Diamonds Direct Inc. - FLORIDA'),
  ('Diamonds Evermore'),
  ('Diamonds On Wabash'),
  ('Diamonds and Dogs'),
  ('Diamonds and Gold International, Inc.-MN'),
  ('Diamonds and More Inc'),
  ('Diedrich Jewelers'),
  ('Disinger Jewelers of Jasper'),
  ('Dolabany Jewelers, Inc'),
  ('Doland Jewelers'),
  ('Don Victor Jewelers'),
  ('Don''s Jewelry & Design-Washington'),
  ('Don''s Jewelry, Inc. - Clinton'),
  ('Douglas Jeweler Inc.'),
  ('Drake''s Jewelry'),
  ('Dream Jewelers'),
  ('Drenon Jewelry, Inc.'),
  ('Droste''s Jewelry Shoppes'),
  ('Dunbar Jewelers'),
  ('Duncan Jewelry - Osage Beach'),
  ('Dunkin''s Diamonds - Naples'),
  ('Duquet Fine Jewelry Design, Christopher'),
  ('Duvarney Jewelers-C'),
  ('Duvarney Jewelers-F'),
  ('E. Ryan Jewelers'),
  ('EKA Jewelers'),
  ('East Tennessee Diamond Co, Inc.'),
  ('Eaton Turner Jewelry - Helena'),
  ('Eaton''s Fine Jewelry - St Albans'),
  ('Eckerman''s, Inc.-IA'),
  ('Ed & Ethel''s Fine Jewelry'),
  ('Eden Jewelry & Repair - Eden'),
  ('Eden Jewelry (Danville)'),
  ('Eden Jewelry Stores - South Boston'),
  ('Eden Jewelry and Repair of Martinsville, VA'),
  ('Ediger''s Diamonds'),
  ('Edmund''s Jewelers'),
  ('Edward Jewelers, M.- MA'),
  ('Elebash Jewelry Company'),
  ('Elegance Jewelers'),
  ('Elias Diamonds & Repair-T'),
  ('Ell''s Jewelry - Shawnee'),
  ('Elliott Jewelers, Inc.-IA'),
  ('Elliott''s Jewelers - Huntsville'),
  ('Ellis Jewelers - Frankfort'),
  ('Ellis Jewelers - Lexington'),
  ('Ellis Jewelers Inc. - Concord'),
  ('Ellis Jewelers, Inc - Seymour'),
  ('Ellsworth Jewelers'),
  ('Elmquist, Inc.'),
  ('Emigh Jewelry Company (EJC)'),
  ('Engelbert''s Jewelers, Inc.'),
  ('Enhancery Jewelers - CA'),
  ('Eric''s Diamonds - WI'),
  ('Erica DelGardo Jewelry Designs'),
  ('Erica''s Jewelry - IL'),
  ('Erickson Jewelers'),
  ('Erwin''s Jewelers Co'),
  ('FORGE Jewelry Works'),
  ('Faini'),
  ('Falkenberg''s Inc.'),
  ('Falmouth Jewelry Shop'),
  ('Family & Co Jewelers'),
  ('Family JewelBox LLC'),
  ('Farmer''s Jewelry, Inc., W. L.'),
  ('Farr''s Jewelry - UT'),
  ('Farrar Jewelers - NC'),
  ('Federal Way Jewelers'),
  ('Feldstein Jewelers'),
  ('Fernbaugh''s Diamonds and Fine Jewelry'),
  ('Fiebig Jewelers Inc'),
  ('Fielding Jewelry, Inc'),
  ('Finch Jewelers'),
  ('Fire and Ice Jewelry'),
  ('First People''s Jewelers'),
  ('Fliegauf Jewelers Inc.'),
  ('Floyd & Green Fine Jewelers'),
  ('Forbes Jewelers'),
  ('Forever Young Fine Jewelers'),
  ('Fountain City Jewelers'),
  ('Fox Fine Jewelry'),
  ('Frank Jewelers of Freeport'),
  ('Frantz Diamonds & Jewelry'),
  ('Franzetti Jewelers'),
  ('Furnari Jewelers'),
  ('Futer Bros, Inc'),
  ('G&H Jewelers'),
  ('G.A. Pope Fine Jewelry'),
  ('Gaines Jewelry'),
  ('Gala Jewelers, Inc.'),
  ('Galicia Fine Jewelers'),
  ('Galleria Fine Jewelry'),
  ('Garrick Jewelers, Inc.'),
  ('Gayle''s Jewelers, Inc.'),
  ('Gem Den LLC'),
  ('Gem Gallery - Bozeman'),
  ('Gem Jewelers of Ada, Inc.'),
  ('Gem Smith Inc. (The)-UT'),
  ('Gemma Gallery - Pinehurst'),
  ('Gemstone Creations, LLC'),
  ('Gendron''s Jewelers'),
  ('Genesis Jewelers of Yorktown'),
  ('Geneva Jewelry'),
  ('Genna Jewelers'),
  ('Georgetown Jewelers'),
  ('Gerald''s Jewelry - WA'),
  ('Germani''s Jewelry Inc.'),
  ('Gerster Jewelry'),
  ('Gervais Diamond Center - MON'),
  ('Gervais Jewelry & Gifts - MOR'),
  ('Gholson Originals Fine Jewelry'),
  ('Gilbert Jewelers'),
  ('Glasscock Jewelry Corner, Inc.'),
  ('Glennpeter Jewelers'),
  ('Godwin Jewelers Inc.'),
  ('Gold & Gems Fine Jewelry - OR'),
  ('Gold Corner (The) - KS'),
  ('Gold Designs Inc - Bradenton'),
  ('Gold In Art Jewelers - Mount Dora'),
  ('Gold Mine Fine Jewelry - North Carolina'),
  ('Gold Mine Jewelers- California'),
  ('Gold Rush Jewelers- Prudenville'),
  ('Gold Thumb Jewelry Creations Inc'),
  ('Gold and More Jewelers - Liberty'),
  ('Golden Dreams Jewelry- MS'),
  ('Golden Gifts Jewelry - PA'),
  ('Goldmine Jewelry- Saint Ignace'),
  ('Goldsmith Co.Jewelers - UT'),
  ('Goldsmith Gallery - AK'),
  ('Goldsmith Gallery Jewelers - MT'),
  ('Goldsmith Gallery LTD- IA'),
  ('Goldsmith, (The)-WI'),
  ('Goldstein - Pitard - AL'),
  ('Goldworks - Half Moon Bay'),
  ('Goodman & Sons Jewelers - VA'),
  ('Goodman Jewelers of Abingdon'),
  ('Goodman Jewelers of Chilhowie'),
  ('Grace Jewelers - Black Mountain'),
  ('Grace Jewelry - Columbus'),
  ('Grace Marie'),
  ('Grader Jewelers, Inc.'),
  ('Graeber Jewelers'),
  ('Graham Jewelers - Wayzata'),
  ('Graham Jewelers - White Bear Lake'),
  ('Graham Jewelry - Comanche OK'),
  ('Grant Laughter Jewelry, Inc'),
  ('Gray Jewelers, E.B.- Tennessee'),
  ('Gray''s Jewelry & Gifts-B'),
  ('Green Brothers Jewelers - TEXAS'),
  ('Green''s Jewelers Inc  Roxboro'),
  ('Greg Beckman Jewelers, Inc.'),
  ('Greg Lynn Jewelers Inc.'),
  ('Gregory Jewelers - Morganton'),
  ('Gregory''s Jewelers Inc - Lillington'),
  ('Griffith Jewelers'),
  ('Griner Jewelry'),
  ('Gross, Paul Jewelers'),
  ('Gwen''s Fine Jewelers'),
  ('Hager Jewelry Inc.'),
  ('Hall of Greetings, Inc./Greetings Jewelers'),
  ('Hamilton Jewelers'),
  ('Hancock Jewelers'),
  ('Hannon Jeweler, (Warren)'),
  ('Hanson''s Fine Jewelry-A'),
  ('Harkleroad Diamonds and Fine Jewelry'),
  ('Harold''s Jewelry Store-MO'),
  ('Harper Jewelry Co., Inc'),
  ('Harris Jeweler   - OH'),
  ('Harris Jewelers - Rio Rancho'),
  ('Harrison''s Jewelry Company- WA'),
  ('Hart''s Jewelry - NY'),
  ('Hart''s Jewelry-MI'),
  ('Hartman Jewelers'),
  ('Harvey Oaks Jeweler'),
  ('Hawthorne Jewelry'),
  ('Hayden Jewelers'),
  ('Hayman, David Jewellers'),
  ('Haywood''s Inc. - Rocky Mount'),
  ('Heiser''s Jewelry'),
  ('Heisey''s Jewelry Company'),
  ('Helker Jewelry - Platteville'),
  ('Hellberg''s Jewelers'),
  ('Heller Jewelers - San Ramon'),
  ('Henderson & Co Jewelers, Inc'),
  ('Henley Jewelers, Inc.'),
  ('Henry''s Fine Jewelry - Basking Ridge'),
  ('Henry''s Fine Jewelry - Summit'),
  ('Herberts Ltd.'),
  ('Heritage Jewelers'),
  ('Herteen & Stocker, Inc.'),
  ('Herzog Jewelers'),
  ('Hi Ho Silver, Inc'),
  ('Hill''s In-House Jewelers LLC'),
  ('Hillsdale Jewelers'),
  ('Hobbs Jewelers'),
  ('Hodges Jewelers - MICHIGAN'),
  ('Hodges Jewelry Co. - Pelham'),
  ('Hodges Jewelry Company - Camilla'),
  ('Hoff Jewelers Inc.'),
  ('Hogan''s Jewelers'),
  ('Hogue''s Jewelry Inc.'),
  ('Holland''s Jewelers Inc.'),
  ('Holliday Jewelry'),
  ('Hollingsworth Jewelers Gallery'),
  ('Hollis & Company Jewelers - LA'),
  ('Holly McHone Jewelers - Oregon'),
  ('Holly''s Jewelry - Arkansas'),
  ('Holstrom''s'),
  ('Holt''s Jewelry - W'),
  ('Hometown Jewelers'),
  ('Honeycutt Jewelers'),
  ('Hoover Jewelers - KS'),
  ('Hoover''s Jewelers - TN'),
  ('Hope Jewelers'),
  ('Horlacher Jewelers, Inc.'),
  ('Horne Custom Jewelry'),
  ('House Of Stones'),
  ('Howard''s - NE'),
  ('Howards - GA'),
  ('Howes & Howes, Inc.-MN'),
  ('Hoyal Jewelry'),
  ('Hudson - Poole Jewelers Inc.'),
  ('Hudson Jewelers Inc.- Ohio'),
  ('Hudson Valley Goldsmith, Ltd.'),
  ('Hugh''s Jewelers - Colorado'),
  ('Hughes Jewelers - Alabama'),
  ('Hunn Co., Inc., Thomas-CO'),
  ('Hunn Jewelers Inc., Robert-MO'),
  ('Huntington Fine Jewelers'),
  ('Huntington Fine Jewelers - Shawnee'),
  ('Hupp Jewelers'),
  ('Hustedt Jewelers'),
  ('Hutcherson Jewelry, Inc'),
  ('I.M. Jewelers'),
  ('Image Jewelry Group, Inc.'),
  ('Imperial Jewelers'),
  ('Infinger''s Jewelry'),
  ('Infinity Custom Jewelers, LLC -Gahanna'),
  ('Innovative Custom Jewelry'),
  ('Intrigue Jewelers'),
  ('Iroff and Son Jewelers'),
  ('J David Jewelry - 101st Street'),
  ('J David Jewelry - Peoria Ave'),
  ('J David Jewelry- Broken Arrow'),
  ('J Jay Walsh Jewelers'),
  ('J L Winters Jewelers'),
  ('J Mullins Jewelry & Gifts'),
  ('J Tabor Jewelers'),
  ('J. A. Jewelers & Co'),
  ('J. F. Kruse Jewelers'),
  ('J. Foster Jewelers'),
  ('J. Parkerson Jewelers - MS'),
  ('J. Thomas Jewelers - MI'),
  ('J. West Jewelers'),
  ('J.C. Grant Company'),
  ('J.R. Fox Jewelers - IN'),
  ('JC Jewelers'),
  ('JJ Jewelers'),
  ('JMR Jewelers'),
  ('JR Dunn Jewelers - NC'),
  ('JR Hofstetter, The Family Jeweler'),
  ('Jackson Diamond Jewelry-OK'),
  ('Jackson Jewelry, M.E.-IL'),
  ('Jacob Matthew Jewelers Inc.'),
  ('James & Sons Fine Jewelers'),
  ('James Gattas Jewelers'),
  ('James Martin Jewelers'),
  ('James Wolf Jewelers'),
  ('Jandron''s Fine Jlry. Inc.'),
  ('Jay Flaming Jewelers'),
  ('Jay''s Jewelry'),
  ('Jayson Jewelers, Inc.'),
  ('Jeff Dennis Jewelers'),
  ('Jefferson Estate Jewelers'),
  ('Jeffrey Jewelry, Inc.'),
  ('Jerry''s Jewelers'),
  ('Jewel Art, LLC'),
  ('Jewel in the Sea'),
  ('Jeweler''s Bench, LLC -TN'),
  ('Jeweler, The- Excelsior'),
  ('Jewelers Workshop Inc.'),
  ('Jewelry Artisans - Atlanta'),
  ('Jewelry Box of Lakeland, The'),
  ('Jewelry Connection (The) -MO'),
  ('Jewelry Connection - TX'),
  ('Jewelry Design Center - Kennewick'),
  ('Jewelry Design Center - Missoula'),
  ('Jewelry Design Center - Spokane'),
  ('Jewelry Design Gallery - NJ'),
  ('Jewelry Doctors'),
  ('Jewelry Emporium, The- TN'),
  ('Jewelry Expressions Inc.'),
  ('Jewelry Shop, The - WI DBA Beth''s Jewelry Shop'),
  ('Jewelry Source, The'),
  ('Jewelry Station, Inc. (The)'),
  ('Jewelry Vault, The'),
  ('Jewelry Works - Minnetonka'),
  ('Jewels By Design'),
  ('Jim Bartlett Fine Jewelry'),
  ('Jim''s Gems-MO'),
  ('Jim''s Jewelers, Inc.-TX'),
  ('Jo & Co Jewelers'),
  ('Joe Tonos Jewelers, Inc.'),
  ('John Atencio'),
  ('John Brasfield Jewelers - COVINGTON'),
  ('John Thomas Jewelers - NM'),
  ('John''s Jewelry LTD.-KS'),
  ('Johnson Jewelers Inc. - AL'),
  ('Johnson Jewelry-MN'),
  ('Johnson the Jeweler-AR'),
  ('Johnson''s Fine Jewelry, J.L.-IN'),
  ('Johnson, Co., Inc.- NE'),
  ('Johnston Jewelers - IL'),
  ('Jon''s Fine Jewelry - FL'),
  ('Jonathan''s Jewelry - Utah'),
  ('Jones Jeweler - Ohio'),
  ('Jones Jewelers, J.F.  -  NY'),
  ('Jordan Jewelers'),
  ('Joseph Jewelers - GA'),
  ('Joseph Jewelers, LLC - CT'),
  ('Joseph''s Jewelry-WA'),
  ('Josephs Jewelers-IA'),
  ('Judith Arnell Jewelers'),
  ('Julee''s Jewelry-MN'),
  ('Julie''s Jewels & Gifts-SC'),
  ('Juniper Gem Co.'),
  ('Just For You Jewelry & Gifts'),
  ('Justin''s Watch and Jewelry Shop'),
  ('K. Hollis Jewelers - IL'),
  ('K. Westphal Jewelers - Andover'),
  ('KT Diamond Jewelers'),
  ('Karadema Inc'),
  ('Karen''s Jewelers Inc'),
  ('Karlise Fine Jewelers'),
  ('Karrow Jewelers'),
  ('Kay Cameron Jewelers'),
  ('Keenan Jewelers - K'),
  ('Keleher''s Jewelry, Inc.'),
  ('Kelley Jewelers'),
  ('Ken Walker Jewelers'),
  ('Kensington Jewelers, Inc'),
  ('Kent Island Jewelry'),
  ('Kent McKenzie Jewelers Inc'),
  ('Kevin Schimke Jewelers'),
  ('Khan Diamonds'),
  ('Kiefer Jewelers'),
  ('Kiger Fine Jewelers'),
  ('Kim''s Fine Jewelry'),
  ('Kimberly-Scott Creations'),
  ('King''s Jewelry - VA'),
  ('Kingston Fine Jewelry'),
  ('Kirk & Company Jewelers'),
  ('Klug''s Country Gold Ltd.'),
  ('Kluh Jewelers, G.L.- Lacey'),
  ('Kluh Jewelers, S.T.'),
  ('Koerber''s Fine Jewelry'),
  ('Komara Jewelers'),
  ('Koser Jewelers'),
  ('Kottke Fine Jewelers, Laurie - M'),
  ('Kottke Jewelers - Owatonna'),
  ('Krekeler Jewelers, Inc.-O''Fal'),
  ('Krekeler Jewelers-Frm'),
  ('Krueger Jewelers - WI'),
  ('Kuhns  Jewelers'),
  ('Kux Jewelers'),
  ('LR Jewelers, Inc.'),
  ('LaBiche Jewelers, LLC'),
  ('LaDon''s Fine Jewelry LLC'),
  ('LaGene Jewelers Inc.'),
  ('Laiti Jewelers - H'),
  ('Lake Oswego Jewelers'),
  ('Lambert Jewelers'),
  ('Landis Jewelers E.G.'),
  ('Lara''s Jewelry and Design'),
  ('Lasker''s Inc.-WI'),
  ('Laudick''s Jewelry, LLC - Van Wert'),
  ('Lauhoff Jewelry & Gifts LLC - C'),
  ('Laura Stanley Personal Jeweler'),
  ('Lauray''s The Diamond Center'),
  ('Lawrence Jewelers'),
  ('Layne''s Jewelry'),
  ('LeRAVe Jewelry'),
  ('Lee Ann''s Fine Jewelry - Conway'),
  ('Lee Ann''s Fine Jewelry Inc. - Russellville'),
  ('Lee Jeweler, AM'),
  ('Legacy Diamond & Gems'),
  ('Legend Jewelers'),
  ('Leibrandt Jewelry Store LLC'),
  ('Leitzel''s Jewelry'),
  ('Leo''s Jewelry & Gifts - MI'),
  ('Leo''s Jewelry - NE'),
  ('Lester Martin Jewelers'),
  ('Linds'),
  ('Liria Gift & Jewelry, Inc'),
  ('Little Gold Mine (The)'),
  ('Little Treasury Jewelers'),
  ('Little''s Jewelers - Corinth'),
  ('Little''s Jewelers - Tupelo'),
  ('Lizzy''s Jewelry/Marysville Pawn'),
  ('Loch Jewelers, Inc.'),
  ('Lodan Design Studio Inc.'),
  ('Long Jewelers III - Chesapeake'),
  ('Long Jewelers, Inc - Virginia Beach'),
  ('Loreena Rose Jewelry'),
  ('Luckey''s Jewelers'),
  ('Luisa Graff Jewelers'),
  ('Luttrell Jewelers'),
  ('Lyla Jewelers'),
  ('M.K. Benatti Jewelers Inc.'),
  ('MARBILL Diamonds and Jewelry'),
  ('MPC Jewelry Design, Inc'),
  ('Madison Avenue Jewelry & Gfts - SC'),
  ('Main Street Jewelry, Inc.'),
  ('Mainland Pawn & Jewelry - TX'),
  ('Maitland Jewelers - FL'),
  ('Makepeace Jewelers'),
  ('Malashock''s Jewelry'),
  ('Mallory''s Creations'),
  ('Malsons Jewelers - 86th Street'),
  ('Malsons Jewelers - Kings Plaza'),
  ('Mann''s Jewelers Inc.'),
  ('Mansour Jewelers'),
  ('Marion''s Jewelry, Inc.'),
  ('Mark Jewellers Inc.-WI'),
  ('Mark Loren Designs'),
  ('Marks Jewelers - Kansas'),
  ('Marks Jewelry - IA'),
  ('Marks of Design, LLC-CT'),
  ('Marlyn Jewelers Inc'),
  ('Marquirette''s Exquisite Jewelry'),
  ('Marthaler Jewelers Inc'),
  ('Martin Jewellers - Shawano'),
  ('Martinique Jewelers'),
  ('Mason Jewelers (Greencastle)'),
  ('Mason Jewelers (Plainfield)'),
  ('Massey Jewelers'),
  ('Master Jewelers'),
  ('Mauk Jewelers Inc.'),
  ('Mauzie''s Fine Jewelry'),
  ('McFerrin''s Jewelry'),
  ('McIntosh Jewelry Inc'),
  ('McKay Jewelers'),
  ('McKenzie and Smiley Jewelers'),
  ('Meadows'' Jewelers'),
  ('Mees Jewelry'),
  ('Mehaffey''s Jewelry'),
  ('Meigs Jewelry'),
  ('Melan Expressions LLC'),
  ('Melancon Jewelers'),
  ('Melby''s Jewelers'),
  ('Melgram Jewelers Inc'),
  ('Melody''s Quality Jewelry'),
  ('Menk  Jewelers, Inc., E.L.'),
  ('Michael & Son''s - NV'),
  ('Michael Eller Diamonds - F'),
  ('Michael Szwed Jewelers'),
  ('Michael''s Creative Jewelry - Phoenix'),
  ('Michael''s Fine Jewelry & Gifts, Inc-LA'),
  ('Michael''s Jewelry - NC'),
  ('Michael''s Reflections in Gold - FL'),
  ('Michele & Company Fine Jewelers -MI'),
  ('Michele Jewelry, Inc. - Texas'),
  ('Mike Wright Jewelers'),
  ('Milano Jewelers'),
  ('Milkins - Monroe'),
  ('Milkins Jewelers - Wyandotte'),
  ('Miller Jewelers, Alan-OH'),
  ('Miller''s Fine Jewelers -WA'),
  ('Miller''s Fine Jewelry, Inc. - MO'),
  ('Miller''s Jewelry - MN'),
  ('Mills Jewelers Inc - NY'),
  ('Minglin Jewelers'),
  ('Miska Jewelers'),
  ('Mississippi Diamond Jewelers'),
  ('Mitchell''s Jewelry (Norman)'),
  ('Mitchener Farrand Fine Jewelry'),
  ('Mitchum Jewelers Inc.'),
  ('Moeller, R.F. Ltd'),
  ('Molinelli''s Jewelers'),
  ('Mon Amie Fine Jewelry'),
  ('Moore Jewelers - TX'),
  ('Moore''s Jewelers, Inc. - MS'),
  ('Morgan''s Jewelers - MN'),
  ('Morning Star Jewelers, Inc.'),
  ('Morris Jewelers - NC'),
  ('Morris Jewelry - KY'),
  ('Morrissey''s Fine Jewelry'),
  ('Moses Jewelers - PA'),
  ('Motif Jewelers'),
  ('Mucklow''s Fine Jewelry'),
  ('Mullen Bros.'),
  ('MurDuff''s, Inc.'),
  ('Murphy Pitard Jewelers'),
  ('Murphy''s Jewelers, Inc. - Magnolia'),
  ('My Jeweler'),
  ('Nacol''s Jewelry'),
  ('Nancy & Co. Fine Jewelers'),
  ('National Jewelry Company'),
  ('Nature Coast Goldsmith Jewelers Inc.'),
  ('Necker Jewelry'),
  ('Neece Jewelers,Inc'),
  ('Needham Jewelers, SE, Inc.'),
  ('Neeter House of Luxury'),
  ('Nelsen''s Fine Jewelry, Inc. - CO'),
  ('Nelson Jewelry'),
  ('Nelson''s Jewelry - Crystal Lake'),
  ('Neugebauer''s Fine Jewelry'),
  ('Niche of Time Jewelry'),
  ('Nick T. Arnold Jewelers, Inc.'),
  ('Noble Jewelers'),
  ('Noe''s Jewelry'),
  ('Nummi Jewelers'),
  ('Nyman Jewelers, Inc.'),
  ('OJB Jewelry, LLC (Eli''s)'),
  ('Oak Valley Jewelers - Oakdale, CA'),
  ('Oaks Jewelers - Berkeley, CA'),
  ('Occasions Fine Jewelry'),
  ('Ocean View Jewelers'),
  ('Oden Watches and Jewelry'),
  ('Old San Juan Jewelers Inc.(The)'),
  ('OldeTowne Jewelers - W'),
  ('Omega Diamond Jewelers'),
  ('Orange City Watch & Jewelry Repair, Inc'),
  ('Orin Jewelers'),
  ('Osborne Jewelers - Goodyear'),
  ('Osborne''s Jewelers - H'),
  ('Osborne''s Jewelers Inc.-A'),
  ('Oz''s Jewelers'),
  ('P.R. Sturgill Fine Jewelry'),
  ('Pace Jewelers, Inc.'),
  ('Pacheco''s Jewelry & Gifts'),
  ('Padgetts Jewelry'),
  ('Pagan''s Jewelry, Inc'),
  ('Palazzo Jewelers'),
  ('Palmer''s Jewelry Inc'),
  ('Pamela''s Fine Jewelry'),
  ('Panowicz Jewelers'),
  ('Park Place Jewelers - Ocean City'),
  ('Parker Jewelers - PA'),
  ('Parker Jewelers- MI'),
  ('Parkers Karat Patch - NC'),
  ('Parks Diamond Jewelers, Inc-TX'),
  ('Parkville Jewelers LLC - MO'),
  ('Parris Jewelers, LLC - MS'),
  ('Pat''s Jewelry Centre, LTD-IA'),
  ('Patina Jewelry + Design'),
  ('Paul Bensel Jewelers'),
  ('Pauls Jewelry Designs'),
  ('Payne Anthony Creative Jewelers'),
  ('Pentaltha, Inc.'),
  ('Perry Jewelers, H., Inc.'),
  ('Perry''s Diamonds & Estate Jewelry - Charlotte'),
  ('Perry''s Emporium Inc.- Wilmington/Shalotte/Hampstead'),
  ('Peter Franklin Jewelers'),
  ('Pettit Jewelers'),
  ('Pharaoh''s Jewelers LLC'),
  ('Phil Jewelers - SC'),
  ('Philip''s Diamond Shop - Marion'),
  ('Pickens, Inc. Jewelers'),
  ('Pickett Brothers Jewelers'),
  ('Pierce Custom Jewelers - FL'),
  ('Pierce Jewelers - IN'),
  ('Piette Jewelers Inc - MA'),
  ('Pineforest Jewelry'),
  ('Piper Diamond Co.'),
  ('Pittman Jewelers'),
  ('Plantation Jewelers Inc.'),
  ('Plateau Jewelers, Inc. - WA'),
  ('Plaza Jewelers -WA'),
  ('Potter''s Jewelry'),
  ('Powell Jewelry'),
  ('Powers & Son Jewelers-TN'),
  ('Prestige Jewelers, Inc. - Hiram'),
  ('Price''s- Minnesota'),
  ('Puckett''s Fine Jewelry - Benton'),
  ('Puckett''s Fine Jewelry - Murray'),
  ('Pugh''s Designer Jewelers - Newark'),
  ('Quality Jewelers - ME'),
  ('Quenan''s Jewelers'),
  ('Quinn''s Diamond Jewelers - SC'),
  ('Quinn''s Goldsmith - Virginia'),
  ('Quinn''s Jewelry Inc. - R'),
  ('R Bruce Carson, Ltd'),
  ('R Gregory Jewelers - Statesville'),
  ('R. Thomas Jewelers'),
  ('R. Westphal Jewelers (Hutchinson)'),
  ('R.J. Jewelers - NY'),
  ('R.M. Johnson & Sons Jewelers'),
  ('RC Wahl Jewelers'),
  ('RN Jewelers'),
  ('Rae''s Jewelry, Inc.'),
  ('Raleigh Diamond Fine Jewelry'),
  ('Randy Arnett Jewelers'),
  ('Randy''s Jewelry, Inc'),
  ('Raskin''s Jewelers'),
  ('Rasmussen Diamonds'),
  ('Rauchs Jewelry Inc -Newton'),
  ('Rawls Jewelers'),
  ('Ray Harp Jewelers'),
  ('Ray Jewelers - NY'),
  ('Ray, Max Jewelers'),
  ('Rebel Diamonds'),
  ('Reck Jewelers, Carl V., Inc.'),
  ('Redlands Jewelers'),
  ('Reed & Sons Jewelers'),
  ('Rees Jewelry LLC'),
  ('Reigning Jewels Fine Jewelry - TX'),
  ('Reiniger Jewelers - Alton'),
  ('Reiniger Jewelers - Ballwin'),
  ('Reiniger Jewelers - Effingham'),
  ('Reiniger Jewelers - Swansea'),
  ('Reiniger Jewelers - Waterloo'),
  ('Renee Taylor Gallery'),
  ('Reusch Jewelers'),
  ('Richard''s Jewelry - Indiana'),
  ('Richter & Phillips Co.'),
  ('Rickie David Jewelers'),
  ('Rihners Jewelers LLC'),
  ('Riley-White Drugs'),
  ('Rinehart Jewelry'),
  ('Ritter Brothers Jewelry & Repair'),
  ('Ritzi Jewelers'),
  ('Robert K. Grant'),
  ('Robert''s Jewelers - Jackson'),
  ('Robert''s Jewelers Inc - SC'),
  ('Roberts Jewelers - Del Rio'),
  ('Roberts Jewelers - Meadville'),
  ('Robichau''s Jewelry'),
  ('Robinette Jewelers - Seneca Falls'),
  ('Robins Jewelry- Collierville'),
  ('Robinson Family Jewelers -Cortland'),
  ('Robson''s Diamond Jewelers - TX'),
  ('Rochester Lapidary Jewelers'),
  ('Rogers Fine Jewelers - TX'),
  ('Rogers Jewelers, Inc. - MI'),
  ('Rogers Jewelry - MA'),
  ('Roman Jewelers'),
  ('Romanation Jewelers'),
  ('Rome Jewelers - Lebanon'),
  ('Rome Jewelers - Xenia'),
  ('Rome Jewelers -Wilmington'),
  ('Rome Jewelers-Hillsboro'),
  ('Roof Jewelers & Awards'),
  ('Root Jewelers'),
  ('Rose Jewelers'),
  ('Rosenfeld Jewelry LTD'),
  ('Ross Elliott Jewelers'),
  ('Ross''s Fine Jewelers'),
  ('Rosson Company'),
  ('Roth Jewelers'),
  ('Rox Jewelers'),
  ('Roy''s Jewelry Store'),
  ('Royal Diadem Jewelers'),
  ('Royal Fine Jewelers - KY'),
  ('Royal Jewelers-IA'),
  ('Ruby Jewelry Co, Inc'),
  ('Runyan''s Jewelers'),
  ('Ruppelius Jewelers'),
  ('Russakoff Jewelers'),
  ('S&E Jewelers - New York'),
  ('SJ Custom Jewelers'),
  ('SVS Fine Jewelry'),
  ('Saginaw Gold & Diamond Center'),
  ('Salem''s Jewelry - Marble Falls'),
  ('Salem''s Jewelry -Burnet'),
  ('Sam Dial Jewelers'),
  ('Sam''s Fine Jewelry - MO'),
  ('Sami Fine Jewelry - AZ'),
  ('Sanborn''s Jewelers'),
  ('Sanders Diamond Jewelers -MD'),
  ('Sanders Jewelry - AL'),
  ('Sartor Hamann Jewelers'),
  ('Sasso'),
  ('Sather Jewelry - WI'),
  ('Sather''s Leading Jewelers, Inc-CO'),
  ('Sawyer Jewelers, Inc.'),
  ('Saxon''s Diamond Centers - Aberdeen'),
  ('Saxon''s Diamond Centers - Bel Air'),
  ('Saxon''s Fine Jewelers - Oregon'),
  ('Sayers Jewelers & Gemologists'),
  ('Schmitt Jewelers - AZ'),
  ('Schwartz Jewelers - C'),
  ('Scott and Sons Fine Jewelry'),
  ('Seever''s Jewelers, LLC'),
  ('Segner''s Jewelers'),
  ('Seibert - House of Gems by J. Seibert'),
  ('Seifert Jewelry'),
  ('Seita Jewelers'),
  ('Select Jewelers'),
  ('Selman''s Jewelers - Gemologists, Inc.'),
  ('Servinsky Jewelers'),
  ('Setterberg Jewelers - AZ'),
  ('Setterberg Jewelers - MN'),
  ('Seven Oaks Fine Jewelers'),
  ('Shains of Lumberton'),
  ('Shannon Fine Jewelry - W'),
  ('Shay''s Jewelers'),
  ('Shelia Bayes Jewelers'),
  ('Shelle Jewelers'),
  ('Shipley''s Fine Jewelry'),
  ('Sickinger''s Jewelry'),
  ('Sierra Moon'),
  ('Signature Jewelers'),
  ('Simons & Son, George'),
  ('Skaneateles Jewelry Inc'),
  ('Skatell''s Jewelers'),
  ('Skewes Jewelry Inc.'),
  ('Sky Diamond Jewelers'),
  ('Smith Jewelers - AL'),
  ('Smith Jewelers Inc. - VA'),
  ('Smith''s of Dublin'),
  ('Snider''s Jewelers Inc. - PA'),
  ('Snyder Jewelers - CO'),
  ('Sohn and McClure Jewelers - Bay Street'),
  ('Sophia''s Jewelry Studio, Ltd.'),
  ('South Miami Jewelers'),
  ('Sovell Jewelry'),
  ('Spalding Jewelry'),
  ('Sparkles Jewelry'),
  ('Spath Jewelers - B'),
  ('Spath Jewelers - V'),
  ('Springer''s Jewelers'),
  ('Spritz Jewelers'),
  ('St John''s Jewelers - Ellicott City'),
  ('Staats Jewelers'),
  ('Stadheim Jewelers of Mason City'),
  ('Stadheim''s - Albert Lea'),
  ('Stall and Kessler''s'),
  ('Stambaugh Jewelers'),
  ('Stark, C.B.'),
  ('State St. Jewelers -NC'),
  ('State Street Jewelers - IL'),
  ('Sterling Jewelers of Connecticut, Inc.'),
  ('Steve Pronko Jewelers'),
  ('Steve''s Jewelry - LA'),
  ('Steven Christopher Jewelers'),
  ('Stockhill Jewelers - Sidn, John'),
  ('Stokes Jewelry'),
  ('Stones Jewelry - W'),
  ('Storey Jewelers'),
  ('Sturhahn Jewelers, Inc. - MO'),
  ('Sturhahn Jewelers-IL'),
  ('Sugar Plum Jewelry Co.'),
  ('Sullivan''s Jewelers, Inc'),
  ('Summerlin Jewelers'),
  ('Sunshine Goldmine'),
  ('Sutton Jewelry'),
  ('Swedes Jewelers'),
  ('Sweet Custom Jewelry'),
  ('Sycamore Jewelers'),
  ('T. Simon Jewelers'),
  ('TTOG'),
  ('Tammy''s Jewelry'),
  ('Tanco Creations'),
  ('Tara & Co. Fine Diamonds'),
  ('Tatge Jewelry - K'),
  ('Taylor Made Jewelry, Inc. - OH'),
  ('Tena''s Jewelry & Gift Shop-E'),
  ('Tenenbaum''s Jewelry'),
  ('Tennie''s Jewelry'),
  ('Texas Gold Connection'),
  ('Thacker Jewelry'),
  ('The Diamond Shop - MISSOURI'),
  ('The Diamond Studio- OH'),
  ('Thollot Diamonds & Fine Jewelry'),
  ('Thomas Jewelers - PA'),
  ('Thomason Jewelers (Earl)-SC'),
  ('Thompson Jewelers - FL'),
  ('Thompson Jewelers-TN'),
  ('Thompson Jewelry, Ken K..-MN'),
  ('Thompson''s Jewelry - AR'),
  ('Thurber''s Jewelry, Inc'),
  ('Tidewater Gold & Diamond'),
  ('Tidwell Jewelers of Greenwood'),
  ('Tidwell Jewelers-Johnston'),
  ('Tillis Jewelry - C'),
  ('Timmreck and McNicol Jewelers'),
  ('Tipton''s Fine Jewelry'),
  ('Tobin Jewelers - Mequon'),
  ('Tobin Jewelers - New Berlin'),
  ('Todd''s Jewelry Repair and Design, LLC'),
  ('Touch of Class Jewelers'),
  ('Towne Square Jewelers LLC-IL'),
  ('Traditions Fine Jewelers'),
  ('Treasure''s Fine Jewelry LLC-IOWA'),
  ('Treasure''s Jewelers - Tennessee'),
  ('Trinity Jewelers - PA'),
  ('Trinkets'),
  ('Tripp & Company Jewelers'),
  ('Turner''s Jewelers, Inc.'),
  ('US Gold Jewelers'),
  ('UniQ Jewelry Gallery'),
  ('Utiger Jewelry, Inc.'),
  ('Vail Creek Jewelry Designs'),
  ('Valentine''s Jewelry LLC'),
  ('Valia''s Jewelers'),
  ('Valle Jewelers - NY'),
  ('Van Denover Jewelry, Inc'),
  ('Van Drake Jewelers'),
  ('Van Duzer Jewelers'),
  ('Van Gundy Jewelers'),
  ('Van Horn Jewelers'),
  ('Vanessa Fine Jewelry'),
  ('Vashti''s Inc'),
  ('Vaughan''s Jewelry & Fine Gifts'),
  ('Vecere Jewelers'),
  ('Venus Jewelers and Gemologists'),
  ('Victoria Marie Jewelers, Inc'),
  ('Vincent J. Jewelers'),
  ('Von''s Inc. - L'),
  ('W.P. Shelton Jewelers'),
  ('Waddington Jewelers'),
  ('Walkers n'' Daughters Jewelers.-ND'),
  ('Walsons & Co.'),
  ('Walter''s Jewelers'),
  ('Walton''s Jewelry'),
  ('Waterfall Jewelers - Wtr'),
  ('Waterfall Jewelers II - W Lake'),
  ('Weber Brothers'),
  ('Weber Jewelry & Gifts -Robinson'),
  ('Weber''s Jewelry - Teutopolis'),
  ('Weber, Raimie H., LLC'),
  ('Weiss Jewelers'),
  ('Welling & Co.'),
  ('Welsh International'),
  ('Wendel''s Diamond Jewelers'),
  ('West End Jewelers'),
  ('Westphal Jewelers, D (Bradley)'),
  ('Wetzel &Truex Jewelers'),
  ('Wexford Jewelers'),
  ('Whidby Jewelers'),
  ('White''s Fine Jewelry'),
  ('Wickersham Jewelry, Inc.'),
  ('Wiersema Jewelry'),
  ('Wiggins'' Jewelers'),
  ('Wild Mountain Fine Jewelers'),
  ('Wild Wood Custom Jewelry'),
  ('Wiley''s Diamonds & Fine Jewelry'),
  ('Wilkerson Jewelers-S'),
  ('William Howard''s Jewelers, Inc.-FL'),
  ('William Williams Rare Jewels'),
  ('Williams Diamond Center - MN'),
  ('Willow Glen Diamond Co'),
  ('Wimmer''s Diamonds'),
  ('Windham Jewelers'),
  ('Windle''s Rock & Jewelry'),
  ('Windmill Park Jewelers'),
  ('Wingo''s Fine Jewelry'),
  ('Wink''s Fine Jewelry'),
  ('Wirt''s Jewelers'),
  ('Witt''s Jewelry'),
  ('Woelk''s House of Diamonds, LLC'),
  ('Wolf & Stag Fine Jewelry'),
  ('Wolf Fine Jewelers - Atlantic City'),
  ('Wolf Fine Jewelers - Middletown'),
  ('Woody''s Jewelry'),
  ('Worthington Jewelers'),
  ('Wright''s Jewelry Store - Fallston'),
  ('Wyatts Diamond Jewelers - Monroe'),
  ('Yanko Jewelers Inc'),
  ('Yates & Co Jewelers, Inc'),
  ('York Jewelers'),
  ('Your Jeweler - ILLINOIS'),
  ('Your Jewelry Box, LLC - PENNSYLVANIA'),
  ('Your Private Jeweler of Lake Norman'),
  ('Z''s Fine Jewelry -AZ'),
  ('Zalman''s Treasures'),
  ('Zembar Jewelers'),
  ('Zimbelman''s Jewelry')
),
rjo_norm AS (
  SELECT name AS raw,
         LOWER(BTRIM(
           REGEXP_REPLACE(
             REGEXP_REPLACE(
               REGEXP_REPLACE(name, '[''.,]', '', 'g'),
               E'\\s+(inc|llc|ltd|co|company)\\.?$', '', 'i'),
             E'\\s+-\\s*.{1,40}$', '', 'i')
         )) AS norm
  FROM rjo_raw
),
stores_norm AS (
  SELECT id, name AS raw,
         LOWER(BTRIM(
           REGEXP_REPLACE(
             REGEXP_REPLACE(
               REGEXP_REPLACE(name, '[''.,]', '', 'g'),
               E'\\s+(inc|llc|ltd|co|company)\\.?$', '', 'i'),
             E'\\s+-\\s*.{1,40}$', '', 'i')
         )) AS norm
  FROM public.trunk_show_stores
),
best_match AS (
  SELECT DISTINCT ON (s.id)
    s.id, s.raw AS store_name, n.raw AS rjo_name,
    similarity(s.norm, n.norm) AS sim
  FROM stores_norm s
  CROSS JOIN rjo_norm n
  ORDER BY s.id, similarity(s.norm, n.norm) DESC, n.raw
)
SELECT
  s.name                                       AS store_name,
  b.rjo_name                                   AS best_rjo_match,
  ROUND(b.sim::numeric, 2)                     AS similarity,
  CASE WHEN EXISTS (
    SELECT 1 FROM public.store_trade_organization_members m
    JOIN public.trade_organizations o ON o.id = m.org_id
    WHERE m.store_id = s.id AND o.name = 'RJO'
  ) THEN 'tagged-RJO' ELSE 'untagged' END      AS status
FROM public.trunk_show_stores s
LEFT JOIN best_match b ON b.id = s.id
ORDER BY status DESC, similarity DESC NULLS LAST, store_name;
